import React, { createContext, useContext, useState, useCallback, useMemo } from 'react';

export type LanguageCode =
  | 'en-IN' // English (India)
  | 'hi'    // Hindi (हिन्दी)
  | 'bn'    // Bengali (বাংলা)
  | 'ta'    // Tamil (தமிழ்)
  | 'te'    // Telugu (తెలుగు)
  | 'mr'    // Marathi (मराठी)
  | 'gu'    // Gujarati (ગુજરાતી)
  | 'kn'    // Kannada (ಕನ್ನಡ)
  | 'ml'    // Malayalam (മലയാളം)
  | 'pa';   // Punjabi (ਪੰਜਾਬੀ)

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
}

export const INDIAN_LANGUAGES: LanguageOption[] = [
  { code: 'en-IN', name: 'English (India)', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  'en-IN': {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.scanner': 'Food Scanner',
    'nav.recommendations': 'Recommendations',
    'nav.aiAssistant': 'AI Assistant',
    'nav.reports': 'Health Reports',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.signOut': 'Sign Out',
    'nav.account': 'Account',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account settings and preferences.',
    'settings.tab.account': 'Account',
    'settings.tab.preferences': 'Preferences',
    'settings.tab.notifications': 'Notifications',
    'settings.tab.security': 'Security',
    'settings.appPreferences': 'App Preferences',
    'settings.appPreferencesDesc': 'Customize your Cura+ experience.',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Toggle dark appearance across the application.',
    'settings.language': 'Language',
    'settings.languageDesc': 'Select your preferred Indian language.',
    'settings.saveChanges': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.notificationsPref': 'Notification Preferences',
    'settings.notificationsDesc': 'Choose what alerts you want to receive.',
    'settings.savePreferences': 'Save Preferences',
    'settings.securityTitle': 'Security',
    'settings.securityDesc': 'Manage your password and security settings.',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',
    'settings.updatePassword': 'Update Password',

    // Recommendations
    'rec.title': 'Recommended For You',
    'rec.subtitle': 'Personalized Indian nutrition based on your health profile, dietary preferences, and allergies.',
    'rec.all': 'All',
    'rec.breakfast': 'Breakfast',
    'rec.lunch': 'Lunch',
    'rec.dinner': 'Dinner',
    'rec.snack': 'Snack',
    'rec.aiSuggest': 'AI Suggest',
    'rec.searchPlaceholder': 'Search food, ingredients, tags...',
    'rec.logMeal': 'Log Meal',
    'rec.logged': 'Logged',
    'rec.calories': 'Calories',
    'rec.protein': 'Protein',
    'rec.carbs': 'Carbs',
    'rec.fat': 'Fat',
    'rec.match': 'Match',

    // Dashboard
    'dash.welcome': 'Welcome back',
    'dash.subtitle': 'Here is your daily personalized health and nutrition summary.',
    'dash.calorieTarget': 'Calorie Target',
    'dash.protein': 'Protein',
    'dash.carbs': 'Carbohydrates',
    'dash.fat': 'Fat',
    'dash.quickActions': 'Quick Actions',
    'dash.scanFood': 'Scan Food',
    'dash.viewRecs': 'View Recommendations',
    'dash.askAi': 'Ask AI Assistant',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'Health Profile',
    'dash.allergies': 'Allergies',
    'dash.vitals': 'Vitals',
    'dash.conditions': 'Conditions',
    'dash.edit': 'Edit',
    'dash.logSubmitted': 'Today\'s Log Submitted',
    'dash.oneSubmission': '1 submission per day',
    'dash.logToday': 'Log Today\'s Metrics',
    'dash.healthScore': 'Health Score',
    'dash.pendingLog': 'Pending Log',
    'dash.active': 'Active',
    'dash.optimal': 'Optimal',
    'dash.bodyMass': 'Body Mass',
    'dash.normalWeight': 'Normal weight',
    'dash.underweight': 'Underweight',
    'dash.overweight': 'Overweight',
    'dash.hydration': 'Hydration',
    'dash.dailySteps': 'Daily Steps',
    'dash.sleepRest': 'Sleep Rest',
    'dash.weeklyTrends': 'Weekly Health Trends',
    'dash.7dayTrends': '7-Day Trends',
    'dash.trendsSubtitle': 'Switch metric to inspect your 7-day progress and daily consistency.',
    'dash.steps': 'Steps',
    'dash.sleep': 'Sleep',
    'dash.water': 'Water',
    'dash.burn': 'Burn',
    'dash.heart': 'Heart',
    'dash.today': 'Today',
    'dash.todaysGoals': 'Today\'s Goals',
    'dash.complete': 'Complete',
    'dash.hydrationGoal': 'Hydration Goal',
    'dash.stepTarget': 'Step Target',
    'dash.restorativeSleep': 'Restorative Sleep',
    'dash.todaysReminders': 'Today\'s Reminders',
    'dash.reminder': 'Reminder',
    'dash.noReminders': 'No active reminders scheduled for today.',
    'dash.addFirstReminder': '+ Add your first reminder',
    'dash.logModalTitle': 'Log Today\'s Health Metrics',
    'dash.logModalSubtitle': 'Enter your daily activity and hydration stats (1 submission per day).',
    'dash.stepsWalked': 'Steps Walked',
    'dash.waterLiters': 'Water (Liters)',
    'dash.sleepHours': 'Sleep (Hours)',
    'dash.caloriesBurned': 'Calories Burned (kcal)',
    'dash.workoutMinutes': 'Workout (Minutes)',
    'dash.autoCalc': 'Auto-calc',
    'dash.cancel': 'Cancel',
    'dash.saveMetrics': 'Save Metrics',
    'dash.saving': 'Saving...',
    'dash.logRecorded': 'Today\'s Log Already Recorded',
    'dash.ruleNotice': 'Cura enforces a 1-log-per-day rule to protect the accuracy of your health analytics. You can log new metrics again tomorrow.',
    'dash.addReminderModal': 'Add Medicine & Health Reminder',
    'dash.medicineName': 'Title / Medicine Name',
    'dash.time': 'Time',
    'dash.dosageNote': 'Dosage / Note (e.g. 500mg after meal)',
    'dash.addReminderBtn': 'Add Reminder',
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',
    'day.sun': 'Sun',
    'ai.title': 'Cura+ AI',
    'ai.subtitle': 'Your 24/7 personal health, nutrition, and wellness companion.',
    'ai.disclaimer': 'Cura+ AI provides informational wellness guidance and may make mistakes. It is not a substitute for professional medical advice. Please consult a qualified healthcare professional.',
    'ai.inputPlaceholder': 'Message Cura+ AI...',
    'ai.thinking': 'Cura+ is thinking...',
    'ai.canIEat': 'Can I eat this?',
    'ai.canIEatDesc': 'Scan food for nutritional analysis',
    'ai.isMedicineSafe': 'Is this medicine safe?',
    'ai.isMedicineSafeDesc': 'Check interactions and side effects',
    'ai.dailyTips': 'Daily Health Tips',
    'ai.dailyTipsDesc': 'Get personalized wellness advice',
    'ai.analyzeHealth': 'Analyze my health',
    'ai.analyzeHealthDesc': 'Review my recent health trends',
    'scanner.title': 'Food Health Scanner',
    'scanner.subtitle': 'Instant clinical AI ingredient safety & allergen detection.',
    'scanner.uploadTab': 'Upload Image',
    'scanner.barcodeTab': 'Barcode Scan',
    'scanner.historyTab': 'Recent Scans',

  },

  'hi': {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.scanner': 'फ़ूड स्कैनर',
    'nav.recommendations': 'आहार सुझाव',
    'nav.aiAssistant': 'एआई सहायक',
    'nav.reports': 'स्वास्थ्य रिपोर्ट्स',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.settings': 'सेटिंग्स',
    'nav.signOut': 'साइन आउट',
    'nav.account': 'खाता',

    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.subtitle': 'अपनी खाता सेटिंग्स और प्राथमिकताओं का प्रबंधन करें।',
    'settings.tab.account': 'खाता',
    'settings.tab.preferences': 'प्राथमिकताएं',
    'settings.tab.notifications': 'सूचनाएं',
    'settings.tab.security': 'सुरक्षा',
    'settings.appPreferences': 'ऐप प्राथमिकताएं',
    'settings.appPreferencesDesc': 'अपने Cura+ अनुभव को अनुकूलित करें।',
    'settings.darkMode': 'डार्क मोड',
    'settings.darkModeDesc': 'डार्क और लाइट थीम के बीच स्विच करें।',
    'settings.language': 'भाषा',
    'settings.languageDesc': 'अपनी पसंदीदा भारतीय भाषा चुनें।',
    'settings.saveChanges': 'बदलाव सहेजें',
    'settings.saving': 'सहेजा जा रहा है...',
    'settings.notificationsPref': 'सूचना प्राथमिकताएं',
    'settings.notificationsDesc': 'चुनें कि आप कौन से अलर्ट प्राप्त करना चाहते हैं।',
    'settings.savePreferences': 'प्राथमिकताएं सहेजें',
    'settings.securityTitle': 'सुरक्षा',
    'settings.securityDesc': 'अपना पासवर्ड और सुरक्षा सेटिंग्स प्रबंधित करें।',
    'settings.currentPassword': 'वर्तमान पासवर्ड',
    'settings.newPassword': 'नया पासवर्ड',
    'settings.confirmPassword': 'नए पासवर्ड की पुष्टि करें',
    'settings.updatePassword': 'पासवर्ड अपडेट करें',

    // Recommendations
    'rec.title': 'आपके लिए अनुशंसित आहार',
    'rec.subtitle': 'आपके स्वास्थ्य प्रोफाइल, एलर्जी और प्राथमिकताओं पर आधारित व्यक्तिगत भारतीय पोषण।',
    'rec.all': 'सभी',
    'rec.breakfast': 'नाश्ता',
    'rec.lunch': 'दोपहर का भोजन',
    'rec.dinner': 'रात का भोजन',
    'rec.snack': 'स्नैक',
    'rec.aiSuggest': 'एआई सुझाव',
    'rec.searchPlaceholder': 'भोजन, सामग्री, टैग खोजें...',
    'rec.logMeal': 'भोजन दर्ज करें',
    'rec.logged': 'दर्ज किया गया',
    'rec.calories': 'कैलोरी',
    'rec.protein': 'प्रोटीन',
    'rec.carbs': 'कार्ब्स',
    'rec.fat': 'फैट',
    'rec.match': 'मैच',

    // Dashboard
    'dash.welcome': 'वापसी पर स्वागत है',
    'dash.subtitle': 'यहाँ आपका दैनिक स्वास्थ्य और पोषण सारांश है।',
    'dash.calorieTarget': 'कैलोरी लक्ष्य',
    'dash.protein': 'प्रोटीन',
    'dash.carbs': 'कार्बोहाइड्रेट',
    'dash.fat': 'फैट',
    'dash.quickActions': 'त्वरित क्रियाएँ',
    'dash.scanFood': 'भोजन स्कैन करें',
    'dash.viewRecs': 'आहार सुझाव देखें',
    'dash.askAi': 'एआई से पूछें',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'स्वास्थ्य प्रोफ़ाइल',
    'dash.allergies': 'एलर्जी',
    'dash.vitals': 'वाइटल्स',
    'dash.conditions': 'स्थितियां',
    'dash.edit': 'संपादित करें',
    'dash.logSubmitted': 'आज का लॉग दर्ज हो गया',
    'dash.oneSubmission': 'प्रतिदिन 1 प्रविष्टि',
    'dash.logToday': 'आज के मेट्रिक्स दर्ज करें',
    'dash.healthScore': 'स्वास्थ्य स्कोर',
    'dash.pendingLog': 'लॉग लंबित',
    'dash.active': 'सक्रिय',
    'dash.optimal': 'उत्कृष्ट',
    'dash.bodyMass': 'शरीर का वजन',
    'dash.normalWeight': 'सामान्य वजन',
    'dash.underweight': 'कम वजन',
    'dash.overweight': 'अधिक वजन',
    'dash.hydration': 'जल संतुलन',
    'dash.dailySteps': 'दैनिक कदम',
    'dash.sleepRest': 'नींद और विश्राम',
    'dash.weeklyTrends': 'साप्ताहिक स्वास्थ्य रुझान',
    'dash.7dayTrends': '7-दिवसीय रुझान',
    'dash.trendsSubtitle': 'अपनी 7-दिन की प्रगति और दैनिक निरंतरता देखने के लिए मीट्रिक बदलें।',
    'dash.steps': 'कदम',
    'dash.sleep': 'नींद',
    'dash.water': 'पानी',
    'dash.burn': 'कैलोरी',
    'dash.heart': 'हृदय गति',
    'dash.today': 'आज',
    'dash.todaysGoals': 'आज के लक्ष्य',
    'dash.complete': 'पूर्ण',
    'dash.hydrationGoal': 'जल लक्ष्य',
    'dash.stepTarget': 'कदम लक्ष्य',
    'dash.restorativeSleep': 'विश्रामदायक नींद',
    'dash.todaysReminders': 'आज के रिमाइंडर्स',
    'dash.reminder': 'रिमाइंडर',
    'dash.noReminders': 'आज के लिए कोई सक्रिय रिमाइंडर नहीं है।',
    'dash.addFirstReminder': '+ अपना पहला रिमाइंडर जोड़ें',
    'dash.logModalTitle': 'आज के स्वास्थ्य मेट्रिक्स दर्ज करें',
    'dash.logModalSubtitle': 'अपनी दैनिक गतिविधि और पानी के आंकड़े दर्ज करें (प्रतिदिन 1 प्रविष्टि)।',
    'dash.stepsWalked': 'चले गए कदम',
    'dash.waterLiters': 'पानी (लीटर)',
    'dash.sleepHours': 'नींद (घंटे)',
    'dash.caloriesBurned': 'जली हुई कैलोरी (kcal)',
    'dash.workoutMinutes': 'व्यायाम (मिनट)',
    'dash.autoCalc': 'स्वचालित गणना',
    'dash.cancel': 'रद्द करें',
    'dash.saveMetrics': 'मेट्रिक्स सहेजें',
    'dash.saving': 'सहेजा जा रहा है...',
    'dash.logRecorded': 'आज का लॉग पहले ही दर्ज किया जा चुका है',
    'dash.ruleNotice': 'सटीक स्वास्थ्य डेटा के लिए Cura प्रतिदिन 1 प्रविष्टि की अनुमति देता है। आप कल नया डेटा दर्ज कर सकते हैं।',
    'dash.addReminderModal': 'दवा और स्वास्थ्य रिमाइंडर जोड़ें',
    'dash.medicineName': 'शीर्षक / दवा का नाम',
    'dash.time': 'समय',
    'dash.dosageNote': 'खुराक / नोट (उदा. भोजन के बाद 500mg)',
    'dash.addReminderBtn': 'रिमाइंडर जोड़ें',
    'day.mon': 'सोम',
    'day.tue': 'मंगल',
    'day.wed': 'बुध',
    'day.thu': 'गुरु',
    'day.fri': 'शुक्र',
    'day.sat': 'शनि',
    'day.sun': 'रवि',
    'ai.title': 'Cura+ एआई',
    'ai.subtitle': 'आपका 24/7 व्यक्तिगत स्वास्थ्य, पोषण और कल्याण साथी।',
    'ai.disclaimer': 'Cura+ AI केवल सूचनात्मक स्वास्थ्य मार्गदर्शन प्रदान करता है। यह पेशेवर चिकित्सा सलाह का विकल्प नहीं है।',
    'ai.inputPlaceholder': 'Cura+ AI को संदेश भेजें...',
    'ai.thinking': 'Cura+ सोच रहा है...',
    'ai.canIEat': 'क्या मैं इसे खा सकता हूँ?',
    'ai.canIEatDesc': 'पोषण विश्लेषण के लिए भोजन स्कैन करें',
    'ai.isMedicineSafe': 'क्या यह दवा सुरक्षित है?',
    'ai.isMedicineSafeDesc': 'दवाओं के प्रभाव और साइड इफेक्ट्स जांचें',
    'ai.dailyTips': 'दैनिक स्वास्थ्य सुझाव',
    'ai.dailyTipsDesc': 'व्यक्तिगत स्वास्थ्य सलाह प्राप्त करें',
    'ai.analyzeHealth': 'मेरे स्वास्थ्य का विश्लेषण करें',
    'ai.analyzeHealthDesc': 'अपने हाल के स्वास्थ्य रुझानों की समीक्षा करें',
    'scanner.title': 'फ़ूड हेल्थ स्कैनर',
    'scanner.subtitle': 'एआई द्वारा तत्काल घटक सुरक्षा और एलर्जी पहचान।',
    'scanner.uploadTab': 'छवि अपलोड करें',
    'scanner.barcodeTab': 'बारकोड स्कैन',
    'scanner.historyTab': 'हाल के स्कैन',

  },

  'bn': {
    // Navigation
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.scanner': 'ফুড স্ক্যানার',
    'nav.recommendations': 'খাদ্য সুপারিশ',
    'nav.aiAssistant': 'এআই সহকারী',
    'nav.reports': 'স্বাস্থ্য রিপোর্ট',
    'nav.profile': 'প্রোফাইল',
    'nav.settings': 'সেটিংস',
    'nav.signOut': 'সাইন আউট',
    'nav.account': 'অ্যাকাউন্ট',

    // Settings
    'settings.title': 'সেটিংস',
    'settings.subtitle': 'আপনার অ্যাকাউন্টের বিবরণ এবং পছন্দসমূহ পরিচালনা করুন।',
    'settings.tab.account': 'অ্যাকাউন্ট',
    'settings.tab.preferences': 'পছন্দসমূহ',
    'settings.tab.notifications': 'বিজ্ঞপ্তি',
    'settings.tab.security': 'নিরাপত্তা',
    'settings.appPreferences': 'অ্যাপ পছন্দসমূহ',
    'settings.appPreferencesDesc': 'আপনার Cura+ অভিজ্ঞতা কাস্টমাইজ করুন।',
    'settings.darkMode': 'ডার্ক মোড',
    'settings.darkModeDesc': 'ডার্ক ও লাইট থিমের মধ্যে পরিবর্তন করুন।',
    'settings.language': 'ভাষা',
    'settings.languageDesc': 'আপনার পছন্দের ভারতীয় ভাষা নির্বাচন করুন।',
    'settings.saveChanges': 'সংরক্ষণ করুন',
    'settings.saving': 'সংরক্ষণ করা হচ্ছে...',
    'settings.notificationsPref': 'বিজ্ঞপ্তি সেটিংস',
    'settings.notificationsDesc': 'আপনি কী ধরণের অ্যালার্ট পেতে চান তা বেছে নিন।',
    'settings.savePreferences': 'পছন্দ সংরক্ষণ করুন',
    'settings.securityTitle': 'নিরাপত্তা',
    'settings.securityDesc': 'পাসওয়ার্ড এবং নিরাপত্তা সেটিংস পরিচালনা করুন।',
    'settings.currentPassword': 'বর্তমান পাসওয়ার্ড',
    'settings.newPassword': 'নতুন পাসওয়ার্ড',
    'settings.confirmPassword': 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
    'settings.updatePassword': 'পাসওয়ার্ড পরিবর্তন করুন',

    // Recommendations
    'rec.title': 'আপনার জন্য প্রস্তাবিত খাবার',
    'rec.subtitle': 'আপনার স্বাস্থ্য প্রোফাইল, অ্যালার্জি এবং খাদ্যাভ্যাসের উপর ভিত্তি করে তৈরি ভারতীয় পুষ্টি তালিকা।',
    'rec.all': 'সমস্ত',
    'rec.breakfast': 'প্রাতরাশ',
    'rec.lunch': 'দুপুরের খাবার',
    'rec.dinner': 'রাতের খাবার',
    'rec.snack': 'জলখাবার',
    'rec.aiSuggest': 'এআই পরামর্শ',
    'rec.searchPlaceholder': 'খাবার, উপকরণ খুঁজুন...',
    'rec.logMeal': 'খাবার যুক্ত করুন',
    'rec.logged': 'যুক্ত হয়েছে',
    'rec.calories': 'ক্যালোরি',
    'rec.protein': 'প্রোটিন',
    'rec.carbs': 'কার্বস',
    'rec.fat': 'ফ্যাট',
    'rec.match': 'ম্যাচ',

    // Dashboard
    'dash.welcome': 'স্বাগতম',
    'dash.subtitle': 'এখানে আপনার দৈনিক পুষ্টি ও স্বাস্থ্যের সামগ্রিক বিবরণ।',
    'dash.calorieTarget': 'ক্যালোরি লক্ষ্য',
    'dash.protein': 'প্রোটিন',
    'dash.carbs': 'কার্বোহাইড্রেট',
    'dash.fat': 'ফ্যাট',
    'dash.quickActions': 'দ্রুত অ্যাকশন',
    'dash.scanFood': 'খাবার স্ক্যান করুন',
    'dash.viewRecs': 'সুপারিশ দেখুন',
    'dash.askAi': 'এআই কে জিজ্ঞাসা করুন',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'স্বাস্থ্য প্রোফাইল',
    'dash.allergies': 'অ্যালার্জি',
    'dash.vitals': 'ভাইটালস',
    'dash.conditions': 'শারীরিক অবস্থা',
    'dash.edit': 'সম্পাদনা করুন',
    'dash.logSubmitted': 'আজকের লগ জমা দেওয়া হয়েছে',
    'dash.oneSubmission': 'প্রতিদিন ১টি জমা',
    'dash.logToday': 'আজকের মেট্রিক্স লগ করুন',
    'dash.healthScore': 'স্বাস্থ্য স্কোর',
    'dash.pendingLog': 'লগ অপেক্ষমান',
    'dash.active': 'সক্রিয়',
    'dash.optimal': 'উত্তম',
    'dash.bodyMass': 'শরীরের ওজন',
    'dash.normalWeight': 'স্বাভাবিক ওজন',
    'dash.underweight': 'কম ওজন',
    'dash.overweight': 'অতিরিক্ত ওজন',
    'dash.hydration': 'জলীয় ভারসাম্য',
    'dash.dailySteps': 'দৈনিক পদক্ষেপ',
    'dash.sleepRest': 'ঘুম ও বিশ্রাম',
    'dash.weeklyTrends': 'সাপ্তাহিক স্বাস্থ্য প্রবণতা',
    'dash.7dayTrends': '৭ দিনের ট্রেন্ডস',
    'dash.trendsSubtitle': '৭ দিনের অগ্রগতি এবং ধারাবাহিকতা দেখতে মেট্রিক পরিবর্তন করুন।',
    'dash.steps': 'কদম',
    'dash.sleep': 'ঘুম',
    'dash.water': 'জল',
    'dash.burn': 'ক্যালোরি',
    'dash.heart': 'হার্ট রেট',
    'dash.today': 'আজ',
    'dash.todaysGoals': 'আজকের লক্ষ্য',
    'dash.complete': 'সম্পূর্ণ',
    'dash.hydrationGoal': 'জল পানের লক্ষ্য',
    'dash.stepTarget': 'হাঁটার লক্ষ্য',
    'dash.restorativeSleep': 'পর্যাপ্ত ঘুম',
    'dash.todaysReminders': 'আজকের অনুস্মারক',
    'dash.reminder': 'অনুস্মারক',
    'dash.noReminders': 'আজকের জন্য কোনো অনুস্মারক নির্ধারিত নেই।',
    'dash.addFirstReminder': '+ আপনার প্রথম অনুস্মারক যোগ করুন',
    'dash.logModalTitle': 'আজকের স্বাস্থ্য মেট্রিক্স লগ করুন',
    'dash.logModalSubtitle': 'আপনার দৈনিক কার্যকলাপ এবং জলের তথ্য লিখুন (প্রতিদিন ১ বার)।',
    'dash.stepsWalked': 'হাঁটা কদম',
    'dash.waterLiters': 'জল (লিটার)',
    'dash.sleepHours': 'ঘুম (ঘণ্টা)',
    'dash.caloriesBurned': 'ক্যালোরি ক্ষয় (kcal)',
    'dash.workoutMinutes': 'ব্যায়াম (মিনিট)',
    'dash.autoCalc': 'অটো হিসাব',
    'dash.cancel': 'বাতিল',
    'dash.saveMetrics': 'মেট্রিক্স সংরক্ষণ করুন',
    'dash.saving': 'সংরক্ষণ হচ্ছে...',
    'dash.logRecorded': 'আজকের লগ ইতিমধ্যে নথিভুক্ত হয়েছে',
    'dash.ruleNotice': 'সঠিক স্বাস্থ্য বিশ্লেষণের জন্য Cura দিনে ১টি লগের অনুমতি দেয়। আপনি আগামীকাল আবার লগ করতে পারেন।',
    'dash.addReminderModal': 'ওষুধ ও স্বাস্থ্য অনুস্মারক যোগ করুন',
    'dash.medicineName': 'শিরোনাম / ওষুধের নাম',
    'dash.time': 'সময়',
    'dash.dosageNote': 'ডোজ / নোট (যেমন খাওয়ার পর ৫০০ মিলিগ্রাম)',
    'dash.addReminderBtn': 'অনুস্মারক যোগ করুন',
    'day.mon': 'সোম',
    'day.tue': 'মঙ্গল',
    'day.wed': 'বুধ',
    'day.thu': 'বৃহঃ',
    'day.fri': 'শুক্র',
    'day.sat': 'শনি',
    'day.sun': 'রবি',
    'ai.title': 'Cura+ এআই',
    'ai.subtitle': 'আপনার ২৪/৭ ব্যক্তিগত স্বাস্থ্য ও পুষ্টি সহকারী।',
    'ai.disclaimer': 'Cura+ AI তথ্যমূলক সুস্থতার নির্দেশনা প্রদান করে। এটি পেশাদার চিকিৎসা পরামর্শের বিকল্প নয়।',
    'ai.inputPlaceholder': 'Cura+ AI কে বার্তা পাঠান...',
    'ai.thinking': 'Cura+ ভাবছে...',
    'ai.canIEat': 'আমি কি এটি খেতে পারি?',
    'ai.canIEatDesc': 'পুষ্টি বিশ্লেষণের জন্য খাবার স্ক্যান করুন',
    'ai.isMedicineSafe': 'এই ওষুধটি কি নিরাপদ?',
    'ai.isMedicineSafeDesc': 'পার্শ্বপ্রতিক্রিয়া ও মিথস্ক্রিয়া পরীক্ষা করুন',
    'ai.dailyTips': 'দৈনিক স্বাস্থ্য পরামর্শ',
    'ai.dailyTipsDesc': 'ব্যক্তিগতকৃত সুস্থতার পরামর্শ নিন',
    'ai.analyzeHealth': 'আমার স্বাস্থ্য বিশ্লেষণ করুন',
    'ai.analyzeHealthDesc': 'সাম্প্রতিক স্বাস্থ্যের প্রবণতা পর্যালোচনা করুন',
    'scanner.title': 'ফুড হেলথ স্ক্যানার',
    'scanner.subtitle': 'উপাদান সুরক্ষা এবং অ্যালার্জেন সনাক্তকরণ।',
    'scanner.uploadTab': 'ছবি আপলোড',
    'scanner.barcodeTab': 'বারকোড স্ক্যান',
    'scanner.historyTab': 'সাম্প্রতিক স্ক্যান',

  },

  'ta': {
    // Navigation
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.scanner': 'உணவு ஸ்கேனர்',
    'nav.recommendations': 'உணவு பரிந்துரைகள்',
    'nav.aiAssistant': 'AI உதவியாளர்',
    'nav.reports': 'சுகாதார அறிக்கைகள்',
    'nav.profile': 'சுயவிவரம்',
    'nav.settings': 'அமைப்புகள்',
    'nav.signOut': 'வெளியேறு',
    'nav.account': 'கணக்கு',

    // Settings
    'settings.title': 'அமைப்புகள்',
    'settings.subtitle': 'உங்கள் கணக்கு அமைப்புகள் மற்றும் விருப்பங்களை நிர்வகிக்கவும்.',
    'settings.tab.account': 'கணக்கு',
    'settings.tab.preferences': 'விருப்பத்தேர்வுகள்',
    'settings.tab.notifications': 'அறிவிப்புகள்',
    'settings.tab.security': 'பாதுகாப்பு',
    'settings.appPreferences': 'பயன்பாட்டு விருப்பங்கள்',
    'settings.appPreferencesDesc': 'உங்கள் Cura+ அனுபவத்தை தனிப்பயனாக்குங்கள்.',
    'settings.darkMode': 'டார்க் பயன்முறை',
    'settings.darkModeDesc': 'டார்க் அல்லது லைட் தோற்றத்திற்கு மாறவும்.',
    'settings.language': 'மொழி',
    'settings.languageDesc': 'உங்கள் விருப்பமான இந்திய மொழியைத் தேர்ந்தெடுக்கவும்.',
    'settings.saveChanges': 'மாற்றங்களைச் சேமிக்கவும்',
    'settings.saving': 'சேமிக்கப்படுகிறது...',
    'settings.notificationsPref': 'அறிவிப்பு விருப்பத்தேர்வுகள்',
    'settings.notificationsDesc': 'நீங்கள் பெற விரும்பும் விழிப்பூட்டல்களைத் தேர்ந்தெடுக்கவும்.',
    'settings.savePreferences': 'விருப்பங்களைச் சேமிக்கவும்',
    'settings.securityTitle': 'பாதுகாப்பு',
    'settings.securityDesc': 'உங்கள் கடவுச்சொல் மற்றும் பாதுகாப்பு அமைப்புகளை நிர்வகிக்கவும்.',
    'settings.currentPassword': 'தற்போதைய கடவுச்சொல்',
    'settings.newPassword': 'புதிய கடவுச்சொல்',
    'settings.confirmPassword': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'settings.updatePassword': 'கடவுச்சொல்லைப் புதுப்பிக்கவும்',

    // Recommendations
    'rec.title': 'உங்களுக்காக பரிந்துரைக்கப்பட்டவை',
    'rec.subtitle': 'உங்கள் சுகாதார சுயவிவரம் மற்றும் உணவு விருப்பங்களின் அடிப்படையிலான ஊட்டச்சத்து.',
    'rec.all': 'அனைத்தும்',
    'rec.breakfast': 'காலை உணவு',
    'rec.lunch': 'மதிய உணவு',
    'rec.dinner': 'இரவு உணவு',
    'rec.snack': 'சிற்றுண்டி',
    'rec.aiSuggest': 'AI பரிந்துரை',
    'rec.searchPlaceholder': 'உணவைத் தேடுங்கள்...',
    'rec.logMeal': 'உணவைப் பதிவுசெய்க',
    'rec.logged': 'பதிவுசெய்யப்பட்டது',
    'rec.calories': 'கலோரிகள்',
    'rec.protein': 'புரதம்',
    'rec.carbs': 'கார்போஹைட்ரேட்',
    'rec.fat': 'கொழுப்பு',
    'rec.match': 'பொருத்தம்',

    // Dashboard
    'dash.welcome': 'மீண்டும் வருக',
    'dash.subtitle': 'உங்கள் தினசரி தனிப்பயனாக்கப்பட்ட சுகாதார சுருக்கம் இங்கே.',
    'dash.calorieTarget': 'கலோரி இலக்கு',
    'dash.protein': 'புரதம்',
    'dash.carbs': 'கார்போஹைட்ரேட்',
    'dash.fat': 'கொழுப்பு',
    'dash.quickActions': 'விரைவு செயல்கள்',
    'dash.scanFood': 'உணவை ஸ்கேன் செய்',
    'dash.viewRecs': 'பரிந்துரைகளைக் காண்க',
    'dash.askAi': 'AI இடம் கேட்கவும்',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'சுகாதார சுயவிவரம்',
    'dash.allergies': 'ஒவ்வாமை',
    'dash.vitals': 'உடல் அறிகுறிகள்',
    'dash.conditions': 'மருத்துவ நிலைமைகள்',
    'dash.edit': 'திருத்து',
    'dash.logSubmitted': 'இன்றைய பதிவு சமர்ப்பிக்கப்பட்டது',
    'dash.oneSubmission': 'நாளைக்கு 1 முறை மட்டுமே',
    'dash.logToday': 'இன்றைய அளவீடுகளைப் பதிவு செய்',
    'dash.healthScore': 'சுகாதார மதிப்பெண்',
    'dash.pendingLog': 'பதிவு நிலுவையில் உள்ளது',
    'dash.active': 'செயலில்',
    'dash.optimal': 'சிறந்தது',
    'dash.bodyMass': 'உடல் எடை',
    'dash.normalWeight': 'இயல்பான எடை',
    'dash.underweight': 'குறைந்த எடை',
    'dash.overweight': 'அதிக எடை',
    'dash.hydration': 'நீரேற்றம்',
    'dash.dailySteps': 'தினசரி படிகள்',
    'dash.sleepRest': 'தூக்கம் & ஓய்வு',
    'dash.weeklyTrends': 'வாராந்திர சுகாதார போக்குகள்',
    'dash.7dayTrends': '7 நாள் போக்குகள்',
    'dash.trendsSubtitle': '7 நாள் முன்னேற்றத்தைக் காண அளவீடுகளை மாற்றவும்.',
    'dash.steps': 'படிகள்',
    'dash.sleep': 'தூக்கம்',
    'dash.water': 'தண்ணீர்',
    'dash.burn': 'எரிந்த கலோரி',
    'dash.heart': 'இதயத் துடிப்பு',
    'dash.today': 'இன்று',
    'dash.todaysGoals': 'இன்றைய இலக்குகள்',
    'dash.complete': 'முடிந்தது',
    'dash.hydrationGoal': 'நீரேற்ற இலக்கு',
    'dash.stepTarget': 'படி இலக்கு',
    'dash.restorativeSleep': 'ஆழ்ந்த தூக்கம்',
    'dash.todaysReminders': 'இன்றைய நினைவூட்டல்கள்',
    'dash.reminder': 'நினைவூட்டல்',
    'dash.noReminders': 'இன்று நினைவூட்டல்கள் எதுவும் இல்லை.',
    'dash.addFirstReminder': '+ முதல் நினைவூட்டலைச் சேர்',
    'dash.logModalTitle': 'இன்றைய சுகாதார அளவீடுகளைப் பதிவு செய்',
    'dash.logModalSubtitle': 'தினசரி நடவடிக்கை மற்றும் தண்ணீர் புள்ளிவிவரங்களை உள்ளிடவும்.',
    'dash.stepsWalked': 'நடந்த படிகள்',
    'dash.waterLiters': 'தண்ணீர் (லிட்டர்)',
    'dash.sleepHours': 'தூக்கம் (மணிநேரம்)',
    'dash.caloriesBurned': 'எரிந்த கலோரி (kcal)',
    'dash.workoutMinutes': 'உடற்பயிற்சி (நிமிடம்)',
    'dash.autoCalc': 'தானியங்கி கணக்கீடு',
    'dash.cancel': 'ரத்து',
    'dash.saveMetrics': 'அளவீடுகளைச் சேமி',
    'dash.saving': 'சேமிக்கிறது...',
    'dash.logRecorded': 'இன்றைய பதிவு ஏற்கனவே முடிந்தது',
    'dash.ruleNotice': 'துல்லியமான பதிவுக்கு ஒரு நாளைக்கு ஒரு முறை மட்டுமே அனுமதிக்கப்படுகிறது.',
    'dash.addReminderModal': 'மருந்து & சுகாதார நினைவூட்டல் சேர்',
    'dash.medicineName': 'மருந்து பெயர்',
    'dash.time': 'நேரம்',
    'dash.dosageNote': 'அளவு / குறிப்பு',
    'dash.addReminderBtn': 'நினைவூட்டல் சேர்',
    'day.mon': 'திங்கள்',
    'day.tue': 'செவ்வாய்',
    'day.wed': 'புதன்',
    'day.thu': 'வியாழன்',
    'day.fri': 'வெள்ளி',
    'day.sat': 'சனி',
    'day.sun': 'ஞாயிறு',
    'ai.title': 'Cura+ AI',
    'ai.subtitle': 'உங்கள் 24/7 தனிப்பட்ட சுகாதார வழிகாட்டி.',
    'ai.disclaimer': 'Cura+ AI தகவல் வழிகாட்டல் மட்டுமே வழங்குகிறது. மருத்துவ ஆலோசனைக்கு மருத்துவரை அணுகவும்.',
    'ai.inputPlaceholder': 'Cura+ AI-க்கு செய்தி அனுப்பவும்...',
    'ai.thinking': 'Cura+ சிந்திக்கிறது...',
    'ai.canIEat': 'இதை நான் சாப்பிடலாமா?',
    'ai.canIEatDesc': 'ஊட்டச்சத்து தகவல்களுக்கு உணவை ஸ்கேன் செய்யவும்',
    'ai.isMedicineSafe': 'இந்த மருந்து பாதுகாப்பானதா?',
    'ai.isMedicineSafeDesc': 'பக்க விளைவுகளைச் சரிபார்க்கவும்',
    'ai.dailyTips': 'தினசரி சுகாதாரக் குறிப்புகள்',
    'ai.dailyTipsDesc': 'தனிப்பயனாக்கப்பட்ட ஆலோசனைகளைப் பெறுங்கள்',
    'ai.analyzeHealth': 'எனது ஆரோக்கியத்தை ஆராயுங்கள்',
    'ai.analyzeHealthDesc': 'சமீபத்திய ஆரோக்கியப் போக்குகளை மதிப்பாய்வு செய்யவும்',
    'scanner.title': 'உணவு சுகாதார ஸ்கேனர்',
    'scanner.subtitle': 'உணவு மூலப்பொருள் பாதுகாப்பு மற்றும் ஒவ்வாமை கண்டறிதல்.',
    'scanner.uploadTab': 'படத்தைப் பதிவேற்று',
    'scanner.barcodeTab': 'பார்கோடு ஸ்கேன்',
    'scanner.historyTab': 'சமீபத்திய ஸ்கேன்கள்',

  },

  'te': {
    // Navigation
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.scanner': 'ఫుడ్ స్కానర్',
    'nav.recommendations': 'ఆహార సిఫార్సులు',
    'nav.aiAssistant': 'AI సహాయకుడు',
    'nav.reports': 'ఆరోగ్య నివేదికలు',
    'nav.profile': 'ప్రొఫైల్',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.signOut': 'సైన్ అవుట్',
    'nav.account': 'ఖాతా',

    // Settings
    'settings.title': 'సెట్టింగ్‌లు',
    'settings.subtitle': 'మీ ఖాతా సెట్టింగ్‌లు మరియు ప్రాధాన్యతలను నిర్వహించండి.',
    'settings.tab.account': 'ఖాతా',
    'settings.tab.preferences': 'ప్రాధాన్యతలు',
    'settings.tab.notifications': 'నోటిఫికేషన్‌లు',
    'settings.tab.security': 'భద్రత',
    'settings.appPreferences': 'యాప్ ప్రాధాన్యతలు',
    'settings.appPreferencesDesc': 'మీ Cura+ అనుభవాన్ని అనుకూలీకరించండి.',
    'settings.darkMode': 'డార్క్ మోడ్',
    'settings.darkModeDesc': 'డార్క్ మరియు లైట్ థీమ్‌లను మార్చండి.',
    'settings.language': 'భాష',
    'settings.languageDesc': 'మీకు ఇష్టమైన భారతీయ భాషను ఎంచుకోండి.',
    'settings.saveChanges': 'మార్పులను సేవ్ చేయండి',
    'settings.saving': 'సేవ్ అవుతోంది...',
    'settings.notificationsPref': 'నోటిఫికేషన్ ప్రాధాన్యతలు',
    'settings.notificationsDesc': 'మీరు ఏ హెచ్చరికలను అందుకోవాలనుకుంటున్నారో ఎంచుకోండి.',
    'settings.savePreferences': 'ప్రాధాన్యతలను సేవ్ చేయండి',
    'settings.securityTitle': 'భద్రత',
    'settings.securityDesc': 'మీ పాస్‌వర్డ్ మరియు భద్రతా సెట్టింగ్‌లను నిర్వహించండి.',
    'settings.currentPassword': 'ప్రస్తుత పాస్‌వర్డ్',
    'settings.newPassword': 'కొత్త పాస్‌వర్డ్',
    'settings.confirmPassword': 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
    'settings.updatePassword': 'పాస్‌వర్డ్‌ను అప్‌డేట్ చేయండి',

    // Recommendations
    'rec.title': 'మీ కోసం సిఫార్సు చేసినవి',
    'rec.subtitle': 'మీ ఆరోగ్య ప్రొఫైల్ ఆధారంగా రూపొందించిన భారతీయ పోషకాహారం.',
    'rec.all': 'అన్నీ',
    'rec.breakfast': 'అల్పాహారం',
    'rec.lunch': 'మధ్యాహ్న భోజనం',
    'rec.dinner': 'రాత్రి భోజనం',
    'rec.snack': 'స్నాక్',
    'rec.aiSuggest': 'AI సూచన',
    'rec.searchPlaceholder': 'ఆహారం లేదా పదార్ధాలను వెతకండి...',
    'rec.logMeal': 'భోజనాన్ని నమోదు చేయండి',
    'rec.logged': 'నమోదు చేయబడింది',
    'rec.calories': 'కేలరీలు',
    'rec.protein': 'ప్రోటీన్',
    'rec.carbs': 'కార్బోహైడ్రేట్లు',
    'rec.fat': 'కొవ్వు',
    'rec.match': 'సరిపోలిక',

    // Dashboard
    'dash.welcome': 'తిరిగి స్వాగతం',
    'dash.subtitle': 'మీ రోజువారీ వ్యక్తిగతీకరించిన ఆరోగ్య సారాంశం ఇక్కడ ఉంది.',
    'dash.calorieTarget': 'కేలరీల లక్ష్యం',
    'dash.protein': 'ప్రోటీన్',
    'dash.carbs': 'కార్బోహైడ్రేట్లు',
    'dash.fat': 'కొవ్వు',
    'dash.quickActions': 'త్వరిత చర్యలు',
    'dash.scanFood': 'ఆహారాన్ని స్కాన్ చేయండి',
    'dash.viewRecs': 'సిఫార్సులను చూడండి',
    'dash.askAi': 'AI ని అడగండి',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'ఆరోగ్య ప్రొఫైల్',
    'dash.allergies': 'అలెర్జీలు',
    'dash.vitals': 'వైటల్స్',
    'dash.conditions': 'ఆరోగ్య పరిస్థితులు',
    'dash.edit': 'సవరించు',
    'dash.logSubmitted': 'ఈరోజు లాగ్ నమోదు చేయబడింది',
    'dash.oneSubmission': 'రోజుకు 1 సారి మాత్రమే',
    'dash.logToday': 'ఈరోజు కొలతలు నమోదు చేయండి',
    'dash.healthScore': 'హెల్త్ స్కోరు',
    'dash.pendingLog': 'లాగ్ పెండింగ్‌లో ఉంది',
    'dash.active': 'యాక్టివ్',
    'dash.optimal': 'అత్యుత్తమ',
    'dash.bodyMass': 'శరీర బరువు',
    'dash.normalWeight': 'సాధారణ బరువు',
    'dash.underweight': 'తక్కువ బరువు',
    'dash.overweight': 'అధిక బరువు',
    'dash.hydration': 'హైడ్రేషన్',
    'dash.dailySteps': 'రోజువారీ అడుగులు',
    'dash.sleepRest': 'నిద్ర & విశ్రాంతి',
    'dash.weeklyTrends': 'వారపు ఆరోగ్య పోకడలు',
    'dash.7dayTrends': '7 రోజుల ట్రెండ్స్',
    'dash.trendsSubtitle': '7 రోజుల పురోగతిని చూడటానికి మెట్రిక్‌లను మార్చండి.',
    'dash.steps': 'అడుగులు',
    'dash.sleep': 'నిద్ర',
    'dash.water': 'నీరు',
    'dash.burn': 'క్యాలరీలు',
    'dash.heart': 'గుండె స్పందన',
    'dash.today': 'ఈ రోజు',
    'dash.todaysGoals': 'ఈరోజు లక్ష్యాలు',
    'dash.complete': 'పూర్తయింది',
    'dash.hydrationGoal': 'నీటి లక్ష్యం',
    'dash.stepTarget': 'అడుగుల లక్ష్యం',
    'dash.restorativeSleep': 'ప్రశాంత నిద్ర',
    'dash.todaysReminders': 'ఈరోజు రిమైండర్లు',
    'dash.reminder': 'రిమైండర్',
    'dash.noReminders': 'ఈరోజు రిమైండర్‌లు లేవు.',
    'dash.addFirstReminder': '+ మొదటి రిమైండర్‌ను జోడించండి',
    'dash.logModalTitle': 'ఈరోజు ఆరోగ్య కొలతలను నమోదు చేయండి',
    'dash.logModalSubtitle': 'రోజువారీ కార్యాచరణ మరియు నీటి వివరాలను నమోదు చేయండి.',
    'dash.stepsWalked': 'నడిచిన అడుగులు',
    'dash.waterLiters': 'నీరు (లీటర్లు)',
    'dash.sleepHours': 'నిద్ర (గంటలు)',
    'dash.caloriesBurned': 'బర్న్ అయిన క్యాలరీలు (kcal)',
    'dash.workoutMinutes': 'వ్యాయామం (నిమిషాలు)',
    'dash.autoCalc': 'ఆటో లెక్కింపు',
    'dash.cancel': 'రద్దు చేయి',
    'dash.saveMetrics': 'మెట్రిక్స్ సేవ్ చేయి',
    'dash.saving': 'సేవ్ అవుతోంది...',
    'dash.logRecorded': 'ఈరోజు లాగ్ ఇప్పటికే నమోదైంది',
    'dash.ruleNotice': 'ఖచ్చితమైన విశ్లేషణ కోసం రోజుకు 1 లాగ్ మాత్రమే అనుమతించబడుతుంది.',
    'dash.addReminderModal': 'మందు & ఆరోగ్య రిమైండర్ జోడించండి',
    'dash.medicineName': 'మందు పేరు',
    'dash.time': 'సమయం',
    'dash.dosageNote': 'మోతాదు / నోట్',
    'dash.addReminderBtn': 'రిమైండర్ జోడించు',
    'day.mon': 'సోమ',
    'day.tue': 'మంగళ',
    'day.wed': 'బుధ',
    'day.thu': 'గురు',
    'day.fri': 'శుక్ర',
    'day.sat': 'శని',
    'day.sun': 'ఆది',
    'ai.title': 'Cura+ AI',
    'ai.subtitle': 'మీ 24/7 వ్యక్తిగత ఆరోగ్య సహాయకుడు.',
    'ai.disclaimer': 'Cura+ AI సమాచార మార్గదర్శకత్వాన్ని మాత్రమే అందిస్తుంది.',
    'ai.inputPlaceholder': 'Cura+ AI కి సందేశం పంపండి...',
    'ai.thinking': 'Cura+ ఆలోచిస్తోంది...',
    'ai.canIEat': 'నేను దీన్ని తినవచ్చా?',
    'ai.canIEatDesc': 'పోషకాహార విశ్లేషణ కోసం ఆహారాన్ని స్కాన్ చేయండి',
    'ai.isMedicineSafe': 'ఈ ఔషధం సురక్షితమేనా?',
    'ai.isMedicineSafeDesc': 'దుష్ప్రభావాలను తనిఖీ చేయండి',
    'ai.dailyTips': 'రోజువారీ ఆరోగ్య చిట్కాలు',
    'ai.dailyTipsDesc': 'వ్యక్తిగతీకరించిన సలహా పొందండి',
    'ai.analyzeHealth': 'నా ఆరోగ్యాన్ని విశ్లేషించండి',
    'ai.analyzeHealthDesc': 'ఇటీవలి ఆరోగ్య పోకడలను సమీక్షించండి',
    'scanner.title': 'ఫుడ్ హెల్త్ స్కానర్',
    'scanner.subtitle': 'ఆహార పదార్థాల భద్రత మరియు అలెర్జీ గుర్తింపు.',
    'scanner.uploadTab': 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
    'scanner.barcodeTab': 'బార్‌కోడ్ స్కాన్',
    'scanner.historyTab': 'ఇటీవలి స్కాన్లు',

  },

  'mr': {
    // Navigation
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.scanner': 'अन्न स्कॅनर',
    'nav.recommendations': 'आहार शिफारसी',
    'nav.aiAssistant': 'एआय सहाय्यक',
    'nav.reports': 'आरोग्य अहवाल',
    'nav.profile': 'प्रोफाइल',
    'nav.settings': 'सेटिंग्ज',
    'nav.signOut': 'बाहेर पडा',
    'nav.account': 'खाते',

    // Settings
    'settings.title': 'सेटिंग्ज',
    'settings.subtitle': 'तुमची खाते सेटिंग्ज आणि प्राधान्ये व्यवस्थापित करा.',
    'settings.tab.account': 'खाते',
    'settings.tab.preferences': 'प्राधान्ये',
    'settings.tab.notifications': 'सूचना',
    'settings.tab.security': 'सुरक्षा',
    'settings.appPreferences': 'ॲप प्राधान्ये',
    'settings.appPreferencesDesc': 'तुमचा Cura+ अनुभव सानुकूलित करा.',
    'settings.darkMode': 'डार्क मोड',
    'settings.darkModeDesc': 'डार्क आणि लाइट मोड स्विच करा.',
    'settings.language': 'भाषा',
    'settings.languageDesc': 'तुमची पसंतीची भारतीय भाषा निवडा.',
    'settings.saveChanges': 'बदल जतन करा',
    'settings.saving': 'जतन करत आहे...',
    'settings.notificationsPref': 'सूचना प्राधान्ये',
    'settings.notificationsDesc': 'तुम्हाला कोणत्या सूचना हव्या आहेत ते निवडा.',
    'settings.savePreferences': 'प्राधान्ये जतन करा',
    'settings.securityTitle': 'सुरक्षा',
    'settings.securityDesc': 'तुमचा पासवर्ड आणि सुरक्षा सेटिंग्ज व्यवस्थापित करा.',
    'settings.currentPassword': 'सध्याचा पासवर्ड',
    'settings.newPassword': 'नवीन पासवर्ड',
    'settings.confirmPassword': 'नवीन पासवर्डची पुष्टी करा',
    'settings.updatePassword': 'पासवर्ड अपडेट करा',

    // Recommendations
    'rec.title': 'तुमच्यासाठी शिफारस केलेले आहार',
    'rec.subtitle': 'तुमच्या आरोग्य प्रोफाइल आणि आहारावर आधारित भारतीय पोषण.',
    'rec.all': 'सर्व',
    'rec.breakfast': 'नाश्ता',
    'rec.lunch': 'दुपारचे जेवण',
    'rec.dinner': 'रात्रीचे जेवण',
    'rec.snack': 'स्नॅक्स',
    'rec.aiSuggest': 'एआय सल्ला',
    'rec.searchPlaceholder': 'अन्न किंवा साहित्य शोधा...',
    'rec.logMeal': 'जेवण नोंदवा',
    'rec.logged': 'नोंदवले',
    'rec.calories': 'कॅलरीज',
    'rec.protein': 'प्रथिने',
    'rec.carbs': 'कर्बोदके',
    'rec.fat': 'चरबी',
    'rec.match': 'साम्य',

    // Dashboard
    'dash.welcome': 'पुन्हा स्वागत आहे',
    'dash.subtitle': 'येथे तुमचा दैनंदिन पोषण आणि आरोग्य सारांश आहे.',
    'dash.calorieTarget': 'कॅलरी लक्ष्य',
    'dash.protein': 'प्रथिने',
    'dash.carbs': 'कर्बोदके',
    'dash.fat': 'चरबी',
    'dash.quickActions': 'जलद कृती',
    'dash.scanFood': 'अन्न स्कॅन करा',
    'dash.viewRecs': 'शिफारसी पहा',
    'dash.askAi': 'एआय ला विचारा',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'आरोग्य प्रोफाइल',
    'dash.allergies': 'ॲलर्जी',
    'dash.vitals': 'व्हायटल्स',
    'dash.conditions': 'आरोग्य स्थिती',
    'dash.edit': 'संपादित करा',
    'dash.logSubmitted': 'आजची नोंद सबमिट झाली',
    'dash.oneSubmission': 'दररोज १ नोंद',
    'dash.logToday': 'आजचे मेट्रिक्स नोंदवा',
    'dash.healthScore': 'आरोग्य स्कोअर',
    'dash.pendingLog': 'नोंद प्रलंबित',
    'dash.active': 'सक्रिय',
    'dash.optimal': 'उत्तम',
    'dash.bodyMass': 'शरीराचे वजन',
    'dash.normalWeight': 'सामान्य वजन',
    'dash.underweight': 'कमी वजन',
    'dash.overweight': 'जास्त वजन',
    'dash.hydration': 'पाण्याचे प्रमाण',
    'dash.dailySteps': 'दैनिक पावले',
    'dash.sleepRest': 'झोप व विश्रांती',
    'dash.weeklyTrends': 'साप्ताहिक आरोग्य ट्रेंड',
    'dash.7dayTrends': '७ दिवसांचा ट्रेंड',
    'dash.trendsSubtitle': '७ दिवसांची प्रगती पाहण्यासाठी मेट्रिक बदला.',
    'dash.steps': 'पावले',
    'dash.sleep': 'झोप',
    'dash.water': 'पाणी',
    'dash.burn': 'कॅलरी',
    'dash.heart': 'हृदयाचे ठोके',
    'dash.today': 'आज',
    'dash.todaysGoals': 'आजची उद्दिष्टे',
    'dash.complete': 'पूर्ण',
    'dash.hydrationGoal': 'पाण्याचे उद्दिष्ट',
    'dash.stepTarget': 'पावलांचे उद्दिष्ट',
    'dash.restorativeSleep': 'शांत झोप',
    'dash.todaysReminders': 'आजचे रिमाइंडर्स',
    'dash.reminder': 'रिमाइंडर',
    'dash.noReminders': 'आजसाठी कोणतेही रिमाइंडर नाही.',
    'dash.addFirstReminder': '+ पहिले रिमाइंडर जोडा',
    'dash.logModalTitle': 'आजचे आरोग्य मेट्रिक्स नोंदवा',
    'dash.logModalSubtitle': 'तुमच्या दैनंदिन हालचाली आणि पाण्याची आकडेवारी नोंदवा.',
    'dash.stepsWalked': 'चाललेली पावले',
    'dash.waterLiters': 'पाणी (लिटर)',
    'dash.sleepHours': 'झोप (तास)',
    'dash.caloriesBurned': 'जळलेल्या कॅलरी (kcal)',
    'dash.workoutMinutes': 'व्यायाम (मिनिटे)',
    'dash.autoCalc': 'स्वयं गणना',
    'dash.cancel': 'रद्द करा',
    'dash.saveMetrics': 'मेट्रिक्स सेव्ह करा',
    'dash.saving': 'सेव्ह होत आहे...',
    'dash.logRecorded': 'आजची नोंद आधीच झाली आहे',
    'dash.ruleNotice': 'अचूक विश्लेषणासाठी Cura दिवसातून १ नोंद करण्यास अनुमती देते.',
    'dash.addReminderModal': 'औषध व आरोग्य रिमाइंडर जोडा',
    'dash.medicineName': 'औषधाचे नाव',
    'dash.time': 'वेळ',
    'dash.dosageNote': 'डोस / नोंद',
    'dash.addReminderBtn': 'रिमाइंडर जोडा',
    'day.mon': 'सोम',
    'day.tue': 'मंगळ',
    'day.wed': 'बुध',
    'day.thu': 'गुरू',
    'day.fri': 'शुक्र',
    'day.sat': 'शनि',
    'day.sun': 'रवि',
    'ai.title': 'Cura+ AI',
    'ai.subtitle': 'तुमचा २४/७ वैयक्तिक आरोग्य मार्गदर्शक.',
    'ai.disclaimer': 'Cura+ AI केवळ माहितीपूर्ण मार्गदर्शन प्रदान करते.',
    'ai.inputPlaceholder': 'Cura+ AI ला संदेश पाठवा...',
    'ai.thinking': 'Cura+ विचार करत आहे...',
    'ai.canIEat': 'मी हे खाऊ शकतो का?',
    'ai.canIEatDesc': 'पोषण मूल्यांसाठी अन्न स्कॅन करा',
    'ai.isMedicineSafe': 'हे औषध सुरक्षित आहे का?',
    'ai.isMedicineSafeDesc': 'दुष्परिणाम तपासा',
    'ai.dailyTips': 'दैनिक आरोग्य टिप्स',
    'ai.dailyTipsDesc': 'वैयक्तिकृत सल्ला मिळवा',
    'ai.analyzeHealth': 'माझ्या आरोग्याचे विश्लेषण करा',
    'ai.analyzeHealthDesc': 'आरोग्य ट्रेंडचे पुनरावलोकन करा',
    'scanner.title': 'फूड हेल्थ स्कॅनर',
    'scanner.subtitle': 'अन्न घटक सुरक्षा व ॲलर्जी ओळख.',
    'scanner.uploadTab': 'फोटो अपलोड करा',
    'scanner.barcodeTab': 'बारकोड स्कॅन',
    'scanner.historyTab': 'अलीकडील स्कॅन',

  },

  'gu': {
    // Navigation
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.scanner': 'ફૂડ સ્કેનર',
    'nav.recommendations': 'ખોરાકની ભલામણો',
    'nav.aiAssistant': 'AI સહાયક',
    'nav.reports': 'આરોગ્ય અહેવાલો',
    'nav.profile': 'પ્રોફાઇલ',
    'nav.settings': 'સેટિંગ્સ',
    'nav.signOut': 'સાઇન આઉટ',
    'nav.account': 'ખાતું',

    // Settings
    'settings.title': 'સેટિંગ્સ',
    'settings.subtitle': 'તમારા એકાઉન્ટ સેટિંગ્સ અને પસંદગીઓનું સંચાલન કરો.',
    'settings.tab.account': 'ખાતું',
    'settings.tab.preferences': 'પસંદગીઓ',
    'settings.tab.notifications': 'સૂચનાઓ',
    'settings.tab.security': 'સુરક્ષા',
    'settings.appPreferences': 'એપ્લિકેશન પસંદગીઓ',
    'settings.appPreferencesDesc': 'તમારા Cura+ અનુભવને કસ્ટમાઇઝ કરો.',
    'settings.darkMode': 'ડાર્ક મોડ',
    'settings.darkModeDesc': 'ડાર્ક અથવા લાઇટ મોડ વચ્ચે ફેરબદલ કરો.',
    'settings.language': 'ભાષા',
    'settings.languageDesc': 'તમારી પસંદગીની ભારતીય ભાષા પસંદ કરો.',
    'settings.saveChanges': 'ફેરફારો સાચવો',
    'settings.saving': 'સાચવી રહ્યું છે...',
    'settings.notificationsPref': 'સૂચના પસંદગીઓ',
    'settings.notificationsDesc': 'તમે કયા ચેતવણીઓ મેળવવા માંગો છો તે પસંદ કરો.',
    'settings.savePreferences': 'પસંદગીઓ સાચવો',
    'settings.securityTitle': 'સુરક્ષા',
    'settings.securityDesc': 'તમારો પાસવર્ડ અને સુરક્ષા સેટિંગ્સ મેનેજ કરો.',
    'settings.currentPassword': 'વર્તમાન પાસવર્ડ',
    'settings.newPassword': 'નવો પાસવર્ડ',
    'settings.confirmPassword': 'નવા પાસવર્ડની પુષ્ટિ કરો',
    'settings.updatePassword': 'પાસવર્ડ અપડેટ કરો',

    // Recommendations
    'rec.title': 'તમારા માટે ભલામણ કરેલ',
    'rec.subtitle': 'તમારી આરોગ્ય પ્રોફાઇલ પર આધારિત વ્યક્તિગત ભારતીય પોષણ.',
    'rec.all': 'બધા',
    'rec.breakfast': 'સવારનો નાસ્તો',
    'rec.lunch': 'બપોરનું ભોજન',
    'rec.dinner': 'રાત્રિભોજન',
    'rec.snack': 'નાસ્તો',
    'rec.aiSuggest': 'AI સૂચન',
    'rec.searchPlaceholder': 'ખોરાક શોધો...',
    'rec.logMeal': 'ભોજન નોંધો',
    'rec.logged': 'નોંધાયેલ',
    'rec.calories': 'કેલરી',
    'rec.protein': 'પ્રોટીન',
    'rec.carbs': 'કાર્બોહાઇડ્રેટ',
    'rec.fat': 'ચરબી',
    'rec.match': 'મેચ',

    // Dashboard
    'dash.welcome': 'પુનઃ સ્વાગત છે',
    'dash.subtitle': 'અહીં તમારો દૈનિક સ્વાસ્થ્ય સારાંશ છે.',
    'dash.calorieTarget': 'કેલરી લક્ષ્ય',
    'dash.protein': 'પ્રોટીન',
    'dash.carbs': 'કાર્બોહાઇડ્રેટ',
    'dash.fat': 'ચરબી',
    'dash.quickActions': 'ઝડપી ક્રિયાઓ',
    'dash.scanFood': 'ખોરાક સ્કેન કરો',
    'dash.viewRecs': 'ભલામણો જુઓ',
    'dash.askAi': 'AI ને પૂછો',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'હેલ્થ પ્રોફાઇલ',
    'dash.allergies': 'એલર્જી',
    'dash.vitals': 'વાઇટલ્સ',
    'dash.conditions': 'શારીરિક પરિસ્થિતિઓ',
    'dash.edit': 'ફેરફાર કરો',
    'dash.logSubmitted': 'આજનો લોગ સબમિટ થયો',
    'dash.oneSubmission': 'દિવસમાં ૧ વખત',
    'dash.logToday': 'આજના મેટ્રિક્સ લોગ કરો',
    'dash.healthScore': 'હેલ્થ સ્કોર',
    'dash.pendingLog': 'લોગ બાકી છે',
    'dash.active': 'સક્રિય',
    'dash.optimal': 'ઉત્તમ',
    'dash.bodyMass': 'શરીરનું વજન',
    'dash.normalWeight': 'સામાન્ય વજન',
    'dash.underweight': 'ઓછું વજન',
    'dash.overweight': 'વધારે વજન',
    'dash.hydration': 'હાઇડ્રેશન',
    'dash.dailySteps': 'દૈનિક પગલાં',
    'dash.sleepRest': 'ઊંઘ અને આરામ',
    'dash.weeklyTrends': 'સાપ્તાહિક આરોગ્ય વલણો',
    'dash.7dayTrends': '૭-દિવસનો ટ્રેન્ડ',
    'dash.trendsSubtitle': '૭-દિવસની પ્રગતિ જોવા માટે મેટ્રિક બદલો.',
    'dash.steps': 'પગલાં',
    'dash.sleep': 'ઊંઘ',
    'dash.water': 'પાણી',
    'dash.burn': 'કેલરી',
    'dash.heart': 'હૃદયના ધબકારા',
    'dash.today': 'આજે',
    'dash.todaysGoals': 'આજના લક્ષ્યો',
    'dash.complete': 'પૂર્ણ',
    'dash.hydrationGoal': 'પાણીનું લક્ષ્ય',
    'dash.stepTarget': 'પગલાંનું લક્ષ્ય',
    'dash.restorativeSleep': 'ગાઢ ઊંઘ',
    'dash.todaysReminders': 'આજના રીમાઇન્ડર્સ',
    'dash.reminder': 'રીમાઇન્ડર',
    'dash.noReminders': 'આજે કોઈ રીમાઇન્ડર નથી.',
    'dash.addFirstReminder': '+ પહેલું રીમાઇન્ડર ઉમેરો',
    'dash.logModalTitle': 'આજના આરોગ્ય મેટ્રિક્સ લોગ કરો',
    'dash.logModalSubtitle': 'તમારી દૈનિક પ્રવૃત્તિ અને પાણીની માહિતી દાખલ કરો.',
    'dash.stepsWalked': 'ચાલેલા પગલાં',
    'dash.waterLiters': 'પાણી (લિટર)',
    'dash.sleepHours': 'ઊંઘ (કલાક)',
    'dash.caloriesBurned': 'બળેલી કેલરી (kcal)',
    'dash.workoutMinutes': 'કસરત (મિનિટ)',
    'dash.autoCalc': 'ઓટો ગણતરી',
    'dash.cancel': 'રદ કરો',
    'dash.saveMetrics': 'મેટ્રિક્સ સાચવો',
    'dash.saving': 'સાચવી રહ્યું છે...',
    'dash.logRecorded': 'આજનો લોગ પહેલાથી નોંધાયેલો છે',
    'dash.ruleNotice': 'ચોક્કસ વિશ્લેષણ માટે દિવસમાં ૧ લોગની મંજૂરી છે.',
    'dash.addReminderModal': 'દવા અને આરોગ્ય રીમાઇન્ડર ઉમેરો',
    'dash.medicineName': 'દવાનું નામ',
    'dash.time': 'સમય',
    'dash.dosageNote': 'ડોઝ / નોંધ',
    'dash.addReminderBtn': 'રીમાઇન્ડર ઉમેરો',
    'day.mon': 'સોમ',
    'day.tue': 'મંગળ',
    'day.wed': 'બુધ',
    'day.thu': 'ગુરુ',
    'day.fri': 'શુક્ર',
    'day.sat': 'શનિ',
    'day.sun': 'રવિ',
    'ai.title': 'Cura+ AI',
    'ai.subtitle': 'તમારો ૨૪/૭ વ્યક્તિગત આરોગ્ય સાથી.',
    'ai.disclaimer': 'Cura+ AI માત્ર માહિતી માટે માર્ગદર્શન પૂરું પાડે છે.',
    'ai.inputPlaceholder': 'Cura+ AI ને સંદેશ મોકલો...',
    'ai.thinking': 'Cura+ વિચારી રહ્યું છે...',
    'ai.canIEat': 'શું હું આ ખાઈ શકું?',
    'ai.canIEatDesc': 'પોષણ મૂલ્યો માટે ખોરાક સ્કેન કરો',
    'ai.isMedicineSafe': 'શું આ દવા સુરક્ષિત છે?',
    'ai.isMedicineSafeDesc': 'આડઅસર તપાસો',
    'ai.dailyTips': 'દૈનિક આરોગ્ય ટિપ્સ',
    'ai.dailyTipsDesc': 'વ્યક્તિગત સલાહ મેળવો',
    'ai.analyzeHealth': 'મારા આરોગ્યનું વિશ્લેષણ કરો',
    'ai.analyzeHealthDesc': 'તાજેતરના આરોગ્ય વલણોની સમીક્ષા કરો',
    'scanner.title': 'ફૂડ હેલ્થ સ્કેનર',
    'scanner.subtitle': 'ઘટકોની સુરક્ષા અને એલર્જી ઓળખ.',
    'scanner.uploadTab': 'છબી અપલોડ કરો',
    'scanner.barcodeTab': 'બારકોડ સ્કેન',
    'scanner.historyTab': 'તાજેતરના સ્કેન',

  },

  'kn': {
    // Navigation
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.scanner': 'ಫುಡ್ ಸ್ಕ್ಯಾನರ್',
    'nav.recommendations': 'ಆಹಾರ ಶಿಫಾರಸುಗಳು',
    'nav.aiAssistant': 'AI ಸಹಾಯಕ',
    'nav.reports': 'ಆರೋಗ್ಯ ವರದಿಗಳು',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.signOut': 'ಸೈನ್ ಔಟ್',
    'nav.account': 'ಖಾತೆ',

    // Settings
    'settings.title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'settings.subtitle': 'ನಿಮ್ಮ ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
    'settings.tab.account': 'ಖಾತೆ',
    'settings.tab.preferences': 'ಆದ್ಯತೆಗಳು',
    'settings.tab.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'settings.tab.security': 'ಭದ್ರತೆ',
    'settings.appPreferences': 'ಅಪ್ಲಿಕೇಶನ್ ಆದ್ಯತೆಗಳು',
    'settings.appPreferencesDesc': 'ನಿಮ್ಮ Cura+ ಅನುಭವವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ.',
    'settings.darkMode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'settings.darkModeDesc': 'ಡಾರ್ಕ್ ಮತ್ತು ಲೈಟ್ ಮೋಡ್ ನಡುವೆ ಬದಲಾಯಿಸಿ.',
    'settings.language': 'ಭಾಷೆ',
    'settings.languageDesc': 'ನಿಮ್ಮ ನೆಚ್ಚಿನ ಭಾರತೀಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    'settings.saveChanges': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    'settings.saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    'settings.notificationsPref': 'ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು',
    'settings.notificationsDesc': 'ನೀವು ಸ್ವೀಕರಿಸಲು ಬಯಸುವ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಆರಿಸಿ.',
    'settings.savePreferences': 'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ',
    'settings.securityTitle': 'ಭದ್ರತೆ',
    'settings.securityDesc': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತು ಭದ್ರತಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
    'settings.currentPassword': 'ಪ್ರಸ್ತುತ ಪಾಸ್‌ವರ್ಡ್',
    'settings.newPassword': 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
    'settings.confirmPassword': 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    'settings.updatePassword': 'ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ',

    // Recommendations
    'rec.title': 'ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
    'rec.subtitle': 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್ ಆಧಾರಿತ ಭಾರತೀಯ ಪೌಷ್ಟಿಕಾಂಶ.',
    'rec.all': 'ಎಲ್ಲಾ',
    'rec.breakfast': 'ಉಪಾಹಾರ',
    'rec.lunch': 'ಮಧ್ಯಾಹ್ನದ ಊಟ',
    'rec.dinner': 'ರಾತ್ರಿಯ ಊಟ',
    'rec.snack': 'ಲಘು ಉಪಾಹಾರ',
    'rec.aiSuggest': 'AI ಸಲಹೆ',
    'rec.searchPlaceholder': 'ಆಹಾರವನ್ನು ಹುಡುಕಿ...',
    'rec.logMeal': 'ಊಟ ದಾಖಲಿಸಿ',
    'rec.logged': 'ದಾಖಲಿಸಲಾಗಿದೆ',
    'rec.calories': 'ಕ್ಯಾಲೋರಿಗಳು',
    'rec.protein': 'ಪ್ರೋಟೀನ್',
    'rec.carbs': 'ಕಾರ್ಬ್ಸ್',
    'rec.fat': 'ಕೊಬ್ಬು',
    'rec.match': 'ಹೊಂದಾಣಿಕೆ',

    // Dashboard
    'dash.welcome': 'ಮರಳಿ ಸುಸ್ವಾಗತ',
    'dash.subtitle': 'ಇಲ್ಲಿ ನಿಮ್ಮ ದೈನಂದಿನ ಆರೋಗ್ಯ ಸಾರಾಂಶವಿದೆ.',
    'dash.calorieTarget': 'ಕ್ಯಾಲೋರಿ ಗುರಿ',
    'dash.protein': 'ಪ್ರೋಟೀನ್',
    'dash.carbs': 'ಕಾರ್ಬೋಹೈಡ್ರೇಟ್ಗಳು',
    'dash.fat': 'ಕೊಬ್ಬು',
    'dash.quickActions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    'dash.scanFood': 'ಆಹಾರ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'dash.viewRecs': 'ಶಿಫಾರಸುಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'dash.askAi': 'AI ಅನ್ನು ಕೇಳಿ',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್',
    'dash.allergies': 'ಅಲರ್ಜಿಗಳು',
    'dash.vitals': 'ವೈಟಲ್ಸ್',
    'dash.conditions': 'ಆರೋಗ್ಯ ಸ್ಥಿತಿಗಳು',
    'dash.edit': 'ತಿದ್ದು',
    'dash.logSubmitted': 'ಇಂದಿನ ಲಾಗ್ ಸಲ್ಲಿಸಲಾಗಿದೆ',
    'dash.oneSubmission': 'ದಿನಕ್ಕೆ 1 ಬಾರಿ ಮಾತ್ರ',
    'dash.logToday': 'ಇಂದಿನ ಮೆಟ್ರಿಕ್ಸ್‌ ಲಾಗ್ ಮಾಡಿ',
    'dash.healthScore': 'ಆರೋಗ್ಯ ಸ್ಕೋರ್',
    'dash.pendingLog': 'ಲಾಗ್ ಬಾಕಿ ಇದೆ',
    'dash.active': 'ಸಕ್ರಿಯ',
    'dash.optimal': 'ಉತ್ತಮ',
    'dash.bodyMass': 'ದೇಹದ ತೂಕ',
    'dash.normalWeight': 'ಸಾಮಾನ್ಯ ತೂಕ',
    'dash.underweight': 'ಕಡಿಮೆ ತೂಕ',
    'dash.overweight': 'ಹೆಚ್ಚು ತೂಕ',
    'dash.hydration': 'ಜಲ ಸಮತೋಲನ',
    'dash.dailySteps': 'ದೈನಂದಿನ ಹೆಜ್ಜೆಗಳು',
    'dash.sleepRest': 'ನಿದ್ರೆ ಮತ್ತು ವಿಶ್ರಾಂತಿ',
    'dash.weeklyTrends': 'ಸಾಪ್ತಾಹಿಕ ಆರೋಗ್ಯ ಪ್ರವೃತ್ತಿಗಳು',
    'dash.7dayTrends': '7-ದಿನಗಳ ಟ್ರೆಂಡ್ಸ್',
    'dash.trendsSubtitle': '7-ದಿನಗಳ ಪ್ರಗತಿಯನ್ನು ಪರಿಶೀಲಿಸಲು ಮೆಟ್ರಿಕ್ ಬದಲಾಯಿಸಿ.',
    'dash.steps': 'ಹೆಜ್ಜೆಗಳು',
    'dash.sleep': 'ನಿದ್ರೆ',
    'dash.water': 'ನೀರು',
    'dash.burn': 'ಕ್ಯಾಲೋರಿ',
    'dash.heart': 'ಹೃದಯ ಬಡಿತ',
    'dash.today': 'ಇಂದು',
    'dash.todaysGoals': 'ಇಂದಿನ ಗುರಿಗಳು',
    'dash.complete': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'dash.hydrationGoal': 'ನೀರಿನ ಗುರಿ',
    'dash.stepTarget': 'ಹೆಜ್ಜೆಯ ಗುರಿ',
    'dash.restorativeSleep': 'ಉತ್ತಮ ನಿದ್ರೆ',
    'dash.todaysReminders': 'ಇಂದಿನ ಜ್ಞಾಪನೆಗಳು',
    'dash.reminder': 'ಜ್ಞಾಪನೆ',
    'dash.noReminders': 'ಇಂದು ಯಾವುದೇ ಜ್ಞಾಪನೆಗಳಿಲ್ಲ.',
    'dash.addFirstReminder': '+ ಮೊದಲ ಜ್ಞಾಪನೆಯನ್ನು ಸೇರಿಸಿ',
    'dash.logModalTitle': 'ಇಂದಿನ ಆರೋಗ್ಯ ಮೆಟ್ರಿಕ್ಸ್‌ ಲಾಗ್ ಮಾಡಿ',
    'dash.logModalSubtitle': 'ನಿಮ್ಮ ದೈನಂದಿನ ಚಟುವಟಿಕೆ ಮತ್ತು ನೀರಿನ ವಿವರ ನಮೂದಿಸಿ.',
    'dash.stepsWalked': 'ನಡೆದ ಹೆಜ್ಜೆಗಳು',
    'dash.waterLiters': 'ನೀರು (ಲೀಟರ್)',
    'dash.sleepHours': 'ನಿದ್ರೆ (ಗಂಟೆಗಳು)',
    'dash.caloriesBurned': 'ಸುಟ್ಟ ಕ್ಯಾಲೋರಿ (kcal)',
    'dash.workoutMinutes': 'ವ್ಯಾಯಾಮ (ನಿಮಿಷಗಳು)',
    'dash.autoCalc': 'ಸ್ವಯಂ ಲೆಕ್ಕಾಚಾರ',
    'dash.cancel': 'ರದ್ದುಮಾಡು',
    'dash.saveMetrics': 'ಮೆಟ್ರಿಕ್ಸ್ ಉಳಿಸಿ',
    'dash.saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    'dash.logRecorded': 'ಇಂದಿನ ಲಾಗ್ ಈಗಾಗಲೇ ದಾಖಲಾಗಿದೆ',
    'dash.ruleNotice': 'ನಿಖರತೆಗಾಗಿ ದಿನಕ್ಕೆ 1 ಲಾಗ್‌ಗೆ ಮಾತ್ರ ಅನುಮತಿಸಲಾಗಿದೆ.',
    'dash.addReminderModal': 'ಔಷಧಿ & ಆರೋಗ್ಯ ಜ್ಞಾಪನೆ ಸೇರಿಸಿ',
    'dash.medicineName': 'ಔಷಧಿಯ ಹೆಸರು',
    'dash.time': 'ಸಮಯ',
    'dash.dosageNote': 'ಪ್ರಮಾಣ / ಟಿಪ್ಪಣಿ',
    'dash.addReminderBtn': 'ಜ್ಞಾಪನೆ ಸೇರಿಸಿ',
    'day.mon': 'ಸೋಮ',
    'day.tue': 'ಮಂಗಳ',
    'day.wed': 'ಬುಧ',
    'day.thu': 'ಗುರು',
    'day.fri': 'ಶುಕ್ರ',
    'day.sat': 'ಶನಿ',
    'day.sun': 'ಭಾನು',
    'ai.title': 'Cura+ AI',
    'ai.subtitle': 'ನಿಮ್ಮ 24/7 ವೈಯಕ್ತಿಕ ಆರೋಗ್ಯ ಸಹಾಯಕ.',
    'ai.disclaimer': 'Cura+ AI ಮಾಹಿತಿಯನ್ನು ಮಾತ್ರ ಒದಗಿಸುತ್ತದೆ.',
    'ai.inputPlaceholder': 'Cura+ AI ಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ...',
    'ai.thinking': 'Cura+ ಯೋಚಿಸುತ್ತಿದೆ...',
    'ai.canIEat': 'ನಾನು ಇದನ್ನು ತಿನ್ನಬಹುದೇ?',
    'ai.canIEatDesc': 'ಪೌಷ್ಟಿಕಾಂಶ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಆಹಾರ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'ai.isMedicineSafe': 'ಈ ಔಷಧಿ ಸುರಕ್ಷಿತವೇ?',
    'ai.isMedicineSafeDesc': 'ಅಡ್ಡಪರಿಣಾಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    'ai.dailyTips': 'ದೈನಂದಿನ ಆರೋಗ್ಯ ಸಲಹೆಗಳು',
    'ai.dailyTipsDesc': 'ವೈಯಕ್ತಿಕ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ',
    'ai.analyzeHealth': 'ನನ್ನ ಆರೋಗ್ಯವನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    'ai.analyzeHealthDesc': 'ಇತ್ತೀಚಿನ ಆರೋಗ್ಯ ಪ್ರವೃತ್ತಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    'scanner.title': 'ಆಹಾರ ಆರೋಗ್ಯ ಸ್ಕ್ಯಾನರ್',
    'scanner.subtitle': 'ಘಟಕಗಳ ಸುರಕ್ಷತೆ ಮತ್ತು ಅಲರ್ಜಿ ಪತ್ತೆ.',
    'scanner.uploadTab': 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'scanner.barcodeTab': 'ಬಾರ್‌ಕೋಡ್ ಸ್ಕ್ಯಾನ್',
    'scanner.historyTab': 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು',

  },

  'ml': {
    // Navigation
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.scanner': 'ഫുഡ് സ്കാനർ',
    'nav.recommendations': 'ഭക്ഷണ നിർദ്ദേശങ്ങൾ',
    'nav.aiAssistant': 'AI സഹായി',
    'nav.reports': 'ആരോഗ്യ റിപ്പോർട്ടുകൾ',
    'nav.profile': 'പ്രൊഫൈൽ',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'nav.signOut': 'ലോഗ് ഔട്ട്',
    'nav.account': 'അക്കൗണ്ട്',

    // Settings
    'settings.title': 'ക്രമീകരണങ്ങൾ',
    'settings.subtitle': 'നിങ്ങളുടെ അക്കൗണ്ട് ക്രമീകരണങ്ങളും മുൻഗണനകളും കൈകാര്യം ചെയ്യുക.',
    'settings.tab.account': 'അക്കൗണ്ട്',
    'settings.tab.preferences': 'മുൻഗണനകൾ',
    'settings.tab.notifications': 'അറിയിപ്പുകൾ',
    'settings.tab.security': 'സുരക്ഷ',
    'settings.appPreferences': 'ആപ്പ് മുൻഗണനകൾ',
    'settings.appPreferencesDesc': 'നിങ്ങളുടെ Cura+ അനുഭവം ഇഷ്ടാനുസൃതമാക്കുക.',
    'settings.darkMode': 'ഡാർക്ക് മോഡ്',
    'settings.darkModeDesc': 'ഡാർക്ക് മോഡും ലൈറ്റ് മോഡും തമ്മിൽ മാറ്റുക.',
    'settings.language': 'ഭാഷ',
    'settings.languageDesc': 'നിങ്ങളുടെ പ്രിയപ്പെട്ട ഇന്ത്യൻ ഭാഷ തിരഞ്ഞെടുക്കുക.',
    'settings.saveChanges': 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    'settings.saving': 'സംരക്ഷിക്കുന്നു...',
    'settings.notificationsPref': 'അറിയിപ്പ് മുൻഗണനകൾ',
    'settings.notificationsDesc': 'നിങ്ങൾക്ക് ലഭിക്കേണ്ട മുന്നറിയിപ്പുകൾ തിരഞ്ഞെടുക്കുക.',
    'settings.savePreferences': 'മുൻഗണനകൾ സംരക്ഷിക്കുക',
    'settings.securityTitle': 'സുരക്ഷ',
    'settings.securityDesc': 'നിങ്ങളുടെ പാസ്‌വേഡും സുരക്ഷാ ക്രമീകരണങ്ങളും കൈകാര്യം ചെയ്യുക.',
    'settings.currentPassword': 'നിലവിലെ പാസ്‌വേഡ്',
    'settings.newPassword': 'പുതിയ പാസ്‌വേഡ്',
    'settings.confirmPassword': 'പുതിയ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'settings.updatePassword': 'പാസ്‌വേഡ് അപ്‌ഡേറ്റ് ചെയ്യുക',

    // Recommendations
    'rec.title': 'നിങ്ങൾക്കായി ശുപാർശ ചെയ്തവ',
    'rec.subtitle': 'നിങ്ങളുടെ ആരോഗ്യ വിവരങ്ങളെ അടിസ്ഥാനമാക്കിയുള്ള പോഷകാഹാരം.',
    'rec.all': 'എല്ലാം',
    'rec.breakfast': 'പ്രഭാതഭക്ഷണം',
    'rec.lunch': 'ഉച്ചഭക്ഷണം',
    'rec.dinner': 'അത്താഴം',
    'rec.snack': 'ലഘുഭക്ഷണം',
    'rec.aiSuggest': 'AI നിർദ്ദേശം',
    'rec.searchPlaceholder': 'ഭക്ഷണം തിരയുക...',
    'rec.logMeal': 'ഭക്ഷണം രേഖപ്പെടുത്തുക',
    'rec.logged': 'രേഖപ്പെടുത്തി',
    'rec.calories': 'കലോറി',
    'rec.protein': 'പ്രോട്ടീൻ',
    'rec.carbs': 'കാർബോഹൈഡ്രേറ്റ്',
    'rec.fat': 'കൊഴുപ്പ്',
    'rec.match': 'പൊരുത്തം',

    // Dashboard
    'dash.welcome': 'സ്വാഗതം',
    'dash.subtitle': 'ഇതാ നിങ്ങളുടെ ദൈനംദിന ആരോഗ്യ സംഗ്രഹം.',
    'dash.calorieTarget': 'കലോറി ലക്ഷ്യം',
    'dash.protein': 'പ്രോട്ടീൻ',
    'dash.carbs': 'കാർബോഹൈഡ്രേറ്റ്',
    'dash.fat': 'കൊഴുപ്പ്',
    'dash.quickActions': 'ദ്രുത പ്രവർത്തനങ്ങൾ',
    'dash.scanFood': 'ഭക്ഷണം സ്കാൻ ചെയ്യുക',
    'dash.viewRecs': 'നിർദ്ദേശങ്ങൾ കാണുക',
    'dash.askAi': 'AI യോട് ചോദിക്കുക',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'ആരോഗ്യ പ്രൊഫൈൽ',
    'dash.allergies': 'അലർജികൾ',
    'dash.vitals': 'വൈറ്റലുകൾ',
    'dash.conditions': 'ആരോഗ്യ അവസ്ഥകൾ',
    'dash.edit': 'എഡിറ്റ്',
    'dash.logSubmitted': 'ഇന്നത്തെ ലോഗ് സമർപ്പിച്ചു',
    'dash.oneSubmission': 'ദിവസേന 1 എൻട്രി മാത്രം',
    'dash.logToday': 'ഇന്നത്തെ അളവുകൾ രേഖപ്പെടുത്തുക',
    'dash.healthScore': 'ആരോഗ്യ സ്കോർ',
    'dash.pendingLog': 'ലോഗ് ബാക്കിയുണ്ട്',
    'dash.active': 'സജീവം',
    'dash.optimal': 'മികച്ചത്',
    'dash.bodyMass': 'ശരീരഭാരം',
    'dash.normalWeight': 'സാധാരണ ഭാരം',
    'dash.underweight': 'ഭാരക്കുറവ്',
    'dash.overweight': 'അമിതഭാരം',
    'dash.hydration': 'ജലാംശം',
    'dash.dailySteps': 'ദിവസേനയുള്ള ചുവടുകൾ',
    'dash.sleepRest': 'ഉറക്കവും വിശ്രമവും',
    'dash.weeklyTrends': 'പ്രതിവാര ആരോഗ്യ പ്രവണതകൾ',
    'dash.7dayTrends': '7-ദിവസത്തെ ട്രെൻഡുകൾ',
    'dash.trendsSubtitle': '7 ദിവസത്തെ പുരോഗതി പരിശോധിക്കാൻ മെട്രിക് മാറ്റുക.',
    'dash.steps': 'ചുവടുകൾ',
    'dash.sleep': 'ഉറക്കം',
    'dash.water': 'വെള്ളം',
    'dash.burn': 'കലോറി',
    'dash.heart': 'ഹൃദയമിടിപ്പ്',
    'dash.today': 'ഇന്ന്',
    'dash.todaysGoals': 'ഇന്നത്തെ ലക്ഷ്യങ്ങൾ',
    'dash.complete': 'പൂർത്തിയായി',
    'dash.hydrationGoal': 'വെള്ളം കുടിക്കൽ ലക്ഷ്യം',
    'dash.stepTarget': 'നടത്ത ലക്ഷ്യം',
    'dash.restorativeSleep': 'ആഴത്തിലുള്ള ഉറക്കം',
    'dash.todaysReminders': 'ഇന്നത്തെ ഓർമ്മപ്പെടുത്തലുകൾ',
    'dash.reminder': 'ഓർമ്മപ്പെടുത്തൽ',
    'dash.noReminders': 'ഇന്ന് ഓർമ്മപ്പെടുത്തലുകൾ ഇല്ല.',
    'dash.addFirstReminder': '+ ആദ്യത്തെ ഓർമ്മപ്പെടുത്തൽ ചേർക്കുക',
    'dash.logModalTitle': 'ഇന്നത്തെ ആരോഗ്യ വിവരങ്ങൾ രേഖപ്പെടുത്തുക',
    'dash.logModalSubtitle': 'നിങ്ങളുടെ പ്രവർത്തനങ്ങളും കുടിച്ച വെള്ളത്തിന്റെ അളവും രേഖപ്പെടുത്തുക.',
    'dash.stepsWalked': 'നടന്ന ചുവടുകൾ',
    'dash.waterLiters': 'വെള്ളം (ലിറ്റർ)',
    'dash.sleepHours': 'ഉറക്കം (മണിക്കൂറുകൾ)',
    'dash.caloriesBurned': 'എരിച്ച കലോറി (kcal)',
    'dash.workoutMinutes': 'വ്യായാമം (മിനിറ്റ്)',
    'dash.autoCalc': 'ഓട്ടോ കണക്കുകൂട്ടൽ',
    'dash.cancel': 'റദ്ദാക്കുക',
    'dash.saveMetrics': 'വിവരങ്ങൾ സംരക്ഷിക്കുക',
    'dash.saving': 'സംരക്ഷിക്കുന്നു...',
    'dash.logRecorded': 'ഇന്നത്തെ ലോഗ് ഇതിനകം രേഖപ്പെടുത്തിയിട്ടുണ്ട്',
    'dash.ruleNotice': 'കൃത്യതയ്ക്കായി ദിവസത്തിൽ 1 ലോഗ് മാത്രമേ അനുവദിക്കൂ.',
    'dash.addReminderModal': 'മരുന്ന് & ആരോഗ്യ ഓർമ്മപ്പെടുത്തൽ ചേർക്കുക',
    'dash.medicineName': 'മരുന്നിന്റെ പേര്',
    'dash.time': 'സമയം',
    'dash.dosageNote': 'ഡോസ് / കുറിപ്പ്',
    'dash.addReminderBtn': 'ഓർമ്മപ്പെടുത്തൽ ചേർക്കുക',
    'day.mon': 'തിങ്കൾ',
    'day.tue': 'ചൊവ്വ',
    'day.wed': 'ബുധൻ',
    'day.thu': 'വ്യാഴം',
    'day.fri': 'വെള്ളി',
    'day.sat': 'ശനി',
    'day.sun': 'ഞായർ',
    'ai.title': 'Cura+ AI',
    'ai.subtitle': 'നിങ്ങളുടെ 24/7 വ്യക്തിഗത ആരോഗ്യ സഹായി.',
    'ai.disclaimer': 'Cura+ AI വിവരങ്ങൾ നൽകാൻ മാത്രമുള്ളതാണ്.',
    'ai.inputPlaceholder': 'Cura+ AI-ക്ക് സന്ദേശമയയ്‌ക്കുക...',
    'ai.thinking': 'Cura+ ചിന്തിക്കുന്നു...',
    'ai.canIEat': 'എനിക്കിത് കഴിക്കാമോ?',
    'ai.canIEatDesc': 'പോഷകാഹാര വിശകലനത്തിനായി ഭക്ഷണം സ്കാൻ ചെയ്യുക',
    'ai.isMedicineSafe': 'ഈ മരുന്ന് സുരക്ഷിതമാണോ?',
    'ai.isMedicineSafeDesc': 'പാർശ്വഫലങ്ങൾ പരിശോധിക്കുക',
    'ai.dailyTips': 'ദിവസേനയുള്ള ആരോഗ്യ നുറുങ്ങുകൾ',
    'ai.dailyTipsDesc': 'വ്യക്തിഗത ആരോഗ്യ ഉപദേശങ്ങൾ നേടുക',
    'ai.analyzeHealth': 'എന്റെ ആരോഗ്യം വിശകലനം ചെയ്യുക',
    'ai.analyzeHealthDesc': 'ആരോഗ്യ പ്രവണതകൾ അവലോകനം ചെയ്യുക',
    'scanner.title': 'ഫുഡ് ഹെൽത്ത് സ്കാനർ',
    'scanner.subtitle': 'ചേരുവകളുടെ സുരക്ഷയും അലർജി കണ്ടെത്തലും.',
    'scanner.uploadTab': 'ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    'scanner.barcodeTab': 'ബാർകോഡ് സ്കാൻ',
    'scanner.historyTab': 'സമീപകാല സ്കാനുകൾ',

  },

  'pa': {
    // Navigation
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.scanner': 'ਫੂਡ ਸਕੈਨਰ',
    'nav.recommendations': 'ਭੋਜਨ ਸਿਫ਼ਾਰਸ਼ਾਂ',
    'nav.aiAssistant': 'AI ਸਹਾਇਕ',
    'nav.reports': 'ਸਿਹਤ ਰਿਪੋਰਟਾਂ',
    'nav.profile': 'ਪ੍ਰੋਫਾਈਲ',
    'nav.settings': 'ਸੈਟਿੰਗਾਂ',
    'nav.signOut': 'ਸਾਈਨ ਆਉਟ',
    'nav.account': 'ਖਾਤਾ',

    // Settings
    'settings.title': 'ਸੈਟਿੰਗਾਂ',
    'settings.subtitle': 'ਆਪਣੀਆਂ ਖਾਤਾ ਸੈਟਿੰਗਾਂ ਅਤੇ ਤਰਜੀਹਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ।',
    'settings.tab.account': 'ਖਾਤਾ',
    'settings.tab.preferences': 'ਤਰਜੀਹਾਂ',
    'settings.tab.notifications': 'ਸੂਚਨਾਵਾਂ',
    'settings.tab.security': 'ਸੁਰੱਖਿਆ',
    'settings.appPreferences': 'ਐਪ ਤਰਜੀਹਾਂ',
    'settings.appPreferencesDesc': 'ਆਪਣੇ Cura+ ਅਨੁਭਵ ਨੂੰ ਅਨੁਕੂਲਿਤ ਕਰੋ।',
    'settings.darkMode': 'ਡਾਰਕ ਮੋਡ',
    'settings.darkModeDesc': 'ਡਾਰਕ ਅਤੇ ਲਾਈਟ ਮੋਡ ਵਿੱਚ ਬਦਲੋ।',
    'settings.language': 'ਭਾਸ਼ਾ',
    'settings.languageDesc': 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਰਤੀ ਭਾਸ਼ਾ ਚੁਣੋ।',
    'settings.saveChanges': 'ਤਬਦੀਲੀਆਂ ਸੰਭਾਲੋ',
    'settings.saving': 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    'settings.notificationsPref': 'ਸੂਚਨਾ ਤਰਜੀਹਾਂ',
    'settings.notificationsDesc': 'ਚੁਣੋ ਕਿ ਤੁਸੀਂ ਕਿਹੜੇ ਅਲਰਟ ਪ੍ਰਾਪਤ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ।',
    'settings.savePreferences': 'ਤਰਜੀਹਾਂ ਸੰਭਾਲੋ',
    'settings.securityTitle': 'ਸੁਰੱਖਿਆ',
    'settings.securityDesc': 'ਆਪਣਾ ਪਾਸਵਰਡ ਅਤੇ ਸੁਰੱਖਿਆ ਸੈਟਿੰਗਾਂ ਪ੍ਰਬੰਧਿਤ ਕਰੋ।',
    'settings.currentPassword': 'ਮੌਜੂਦਾ ਪਾਸਵਰਡ',
    'settings.newPassword': 'ਨਵਾਂ ਪਾਸਵਰਡ',
    'settings.confirmPassword': 'ਨਵੇਂ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'settings.updatePassword': 'ਪਾਸਵਰਡ ਅੱਪਡੇਟ ਕਰੋ',

    // Recommendations
    'rec.title': 'ਤੁਹਾਡੇ ਲਈ ਸਿਫ਼ਾਰਸ਼ ਕੀਤਾ ਗਿਆ',
    'rec.subtitle': 'ਤੁਹਾਡੀ ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਭੋਜਨ ਤਰਜੀਹਾਂ ਤੇ ਆਧਾਰਿਤ ਪੋਸ਼ਣ।',
    'rec.all': 'ਸਾਰੇ',
    'rec.breakfast': 'ਨਾਸ਼ਤਾ',
    'rec.lunch': 'ਦੁਪਹਿਰ ਦਾ ਖਾਣਾ',
    'rec.dinner': 'ਰਾਤ ਦਾ ਖਾਣਾ',
    'rec.snack': 'ਸਨੈਕ',
    'rec.aiSuggest': 'AI ਸੁਝਾਅ',
    'rec.searchPlaceholder': 'ਭੋਜਨ ਖੋਜੋ...',
    'rec.logMeal': 'ਭੋਜਨ ਦਰਜ ਕਰੋ',
    'rec.logged': 'ਦਰਜ ਕੀਤਾ ਗਿਆ',
    'rec.calories': 'ਕੈਲੋਰੀ',
    'rec.protein': 'ਪ੍ਰੋਟੀਨ',
    'rec.carbs': 'ਕਾਰਬੋਹਾਈਡ੍ਰੇਟ',
    'rec.fat': 'ਚਰਬੀ',
    'rec.match': 'ਮੇਲ',

    // Dashboard
    'dash.welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ',
    'dash.subtitle': 'ਇੱਥੇ ਤੁਹਾਡਾ ਰੋਜ਼ਾਨਾ ਸਿਹਤ ਸਾਰਾਂਸ਼ ਹੈ।',
    'dash.calorieTarget': 'ਕੈਲੋਰੀ ਟੀਚਾ',
    'dash.protein': 'ਪ੍ਰੋਟੀਨ',
    'dash.carbs': 'ਕਾਰਬੋਹਾਈਡ੍ਰੇਟ',
    'dash.fat': 'ਚਰਬੀ',
    'dash.quickActions': 'ਤੇਜ਼ ਕਾਰਵਾਈਆਂ',
    'dash.scanFood': 'ਭੋਜਨ ਸਕੈਨ ਕਰੋ',
    'dash.viewRecs': 'ਸਿਫ਼ਾਰਸ਼ਾਂ ਵੇਖੋ',
    'dash.askAi': 'AI ਨੂੰ ਪੁੱਛੋ',
    // Additional Dashboard, AI & Scanner Keys
    'dash.healthProfile': 'ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ',
    'dash.allergies': 'ਐਲਰਜੀ',
    'dash.vitals': 'ਵਾਈਟਲਸ',
    'dash.conditions': 'ਸਿਹਤ ਸਥਿਤੀਆਂ',
    'dash.edit': 'ਸੋਧੋ',
    'dash.logSubmitted': 'ਅੱਜ ਦਾ ਲੌਗ ਦਰਜ ਕੀਤਾ ਗਿਆ',
    'dash.oneSubmission': 'ਰੋਜ਼ਾਨਾ 1 ਇੰਦਰਾਜ',
    'dash.logToday': 'ਅੱਜ ਦੇ ਮੈਟ੍ਰਿਕਸ ਲੌਗ ਕਰੋ',
    'dash.healthScore': 'ਸਿਹਤ ਸਕੋਰ',
    'dash.pendingLog': 'ਲੌਗ ਬਾਕੀ ਹੈ',
    'dash.active': 'ਸਰਗਰਮ',
    'dash.optimal': 'ਬਿਹਤਰੀਨ',
    'dash.bodyMass': 'ਸਰੀਰ ਦਾ ਭਾਰ',
    'dash.normalWeight': 'ਆਮ ਭਾਰ',
    'dash.underweight': 'ਘੱਟ ਭਾਰ',
    'dash.overweight': 'ਵੱਧ ਭਾਰ',
    'dash.hydration': 'ਪਾਣੀ ਦਾ ਸੰਤੁਲਨ',
    'dash.dailySteps': 'ਰੋਜ਼ਾਨਾ ਕਦਮ',
    'dash.sleepRest': 'ਨੀਂਦ ਅਤੇ ਆਰਾਮ',
    'dash.weeklyTrends': 'ਹਫ਼ਤਾਵਾਰੀ ਸਿਹਤ ਰੁਝਾਨ',
    'dash.7dayTrends': '7-ਦਿਨਾਂ ਦੇ ਰੁਝਾਨ',
    'dash.trendsSubtitle': '7-ਦਿਨਾਂ ਦੀ ਤਰੱਕੀ ਦੇਖਣ ਲਈ ਮੈਟ੍ਰਿਕ ਬਦਲੋ।',
    'dash.steps': 'ਕਦਮ',
    'dash.sleep': 'ਨੀਂਦ',
    'dash.water': 'ਪਾਣੀ',
    'dash.burn': 'ਕੈਲੋਰੀ',
    'dash.heart': 'ਦਿਲ ਦੀ ਧੜਕਣ',
    'dash.today': 'ਅੱਜ',
    'dash.todaysGoals': 'ਅੱਜ ਦੇ ਟੀਚੇ',
    'dash.complete': 'ਪੂਰਾ ਹੋਇਆ',
    'dash.hydrationGoal': 'ਪਾਣੀ ਦਾ ਟੀਚਾ',
    'dash.stepTarget': 'ਕਦਮਾਂ ਦਾ ਟੀਚਾ',
    'dash.restorativeSleep': 'ਆਰਾਮਦਾਇਕ ਨੀਂਦ',
    'dash.todaysReminders': 'ਅੱਜ ਦੇ ਰੀਮਾਈਂਡਰ',
    'dash.reminder': 'ਰੀਮਾਈਂਡਰ',
    'dash.noReminders': 'ਅੱਜ ਲਈ ਕੋਈ ਰੀਮਾਈਂਡਰ ਨਹੀਂ ਹੈ।',
    'dash.addFirstReminder': '+ ਪਹਿਲਾ ਰੀਮਾਈਂਡਰ ਜੋੜੋ',
    'dash.logModalTitle': 'ਅੱਜ ਦੇ ਸਿਹਤ ਮੈਟ੍ਰਿਕਸ ਲੌਗ ਕਰੋ',
    'dash.logModalSubtitle': 'ਆਪਣੀ ਰੋਜ਼ਾਨਾ ਗਤੀਵਿਧੀ ਅਤੇ ਪਾਣੀ ਦੇ ਅੰਕੜੇ ਦਰਜ ਕਰੋ।',
    'dash.stepsWalked': 'ਚੱਲੇ ਗਏ ਕਦਮ',
    'dash.waterLiters': 'ਪਾਣੀ (ਲੀਟਰ)',
    'dash.sleepHours': 'ਨੀਂਦ (ਘੰਟੇ)',
    'dash.caloriesBurned': 'ਬਰਨ ਕੀਤੀਆਂ ਕੈਲੋਰੀਆਂ (kcal)',
    'dash.workoutMinutes': 'ਕਸਰਤ (ਮਿੰਟ)',
    'dash.autoCalc': 'ਆਟੋ ਗਣਨਾ',
    'dash.cancel': 'ਰੱਦ ਕਰੋ',
    'dash.saveMetrics': 'ਮੈਟ੍ਰਿਕਸ ਸੰਭਾਲੋ',
    'dash.saving': 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    'dash.logRecorded': 'ਅੱਜ ਦਾ ਲੌਗ ਪਹਿਲਾਂ ਹੀ ਦਰਜ ਹੈ',
    'dash.ruleNotice': 'ਸਹੀ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਪ੍ਰਤੀ ਦਿਨ 1 ਲੌਗ ਦੀ ਆਗਿਆ ਹੈ।',
    'dash.addReminderModal': 'ਦਵਾਈ ਅਤੇ ਸਿਹਤ ਰੀਮਾਈਂਡਰ ਜੋੜੋ',
    'dash.medicineName': 'ਦਵਾਈ ਦਾ ਨਾਮ',
    'dash.time': 'ਸਮਾਂ',
    'dash.dosageNote': 'ਖੁਰਾਕ / ਨੋਟ',
    'dash.addReminderBtn': 'ਰੀਮਾਈਂਡਰ ਜੋੜੋ',
    'day.mon': 'ਸੋਮ',
    'day.tue': 'ਮੰਗਲ',
    'day.wed': 'ਬੁੱਧ',
    'day.thu': 'ਵੀਰ',
    'day.fri': 'ਸ਼ੁੱਕਰ',
    'day.sat': 'ਸ਼ਨੀ',
    'day.sun': 'ਐਤ',
    'ai.title': 'Cura+ AI',
    'ai.subtitle': 'ਤੁਹਾਡਾ 24/7 ਨਿੱਜੀ ਸਿਹਤ ਸਾਥੀ।',
    'ai.disclaimer': 'Cura+ AI ਸਿਰਫ ਜਾਣਕਾਰੀ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।',
    'ai.inputPlaceholder': 'Cura+ AI ਨੂੰ ਸੁਨੇਹਾ ਭੇਜੋ...',
    'ai.thinking': 'Cura+ ਸੋਚ ਰਿਹਾ ਹੈ...',
    'ai.canIEat': 'ਕੀ ਮੈਂ ਇਹ ਖਾ ਸਕਦਾ ਹਾਂ?',
    'ai.canIEatDesc': 'ਪੋਸ਼ਣ ਮੁੱਲ ਲਈ ਭੋਜਨ ਸਕੈਨ ਕਰੋ',
    'ai.isMedicineSafe': 'ਕੀ ਇਹ ਦਵਾਈ ਸੁਰੱਖਿਅਤ ਹੈ?',
    'ai.isMedicineSafeDesc': 'ਮਾੜੇ ਪ੍ਰਭਾਵਾਂ ਦੀ ਜਾਂਚ ਕਰੋ',
    'ai.dailyTips': 'ਰੋਜ਼ਾਨਾ ਸਿਹਤ ਸੁਝਾਅ',
    'ai.dailyTipsDesc': 'ਨਿੱਜੀ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ',
    'ai.analyzeHealth': 'ਮੇਰੀ ਸਿਹਤ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    'ai.analyzeHealthDesc': 'ਸਿਹਤ ਰੁਝਾਨਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰੋ',
    'scanner.title': 'ਫੂਡ ਹੈਲਥ ਸਕੈਨਰ',
    'scanner.subtitle': 'ਸਮੱਗਰੀ ਦੀ ਸੁਰੱਖਿਆ ਅਤੇ ਐਲਰਜੀ ਦੀ ਪਛਾਣ।',
    'scanner.uploadTab': 'ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ',
    'scanner.barcodeTab': 'ਬਾਰਕੋਡ ਸਕੈਨ',
    'scanner.historyTab': 'ਹਾਲੀਆ ਸਕੈਨ',

  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, defaultText?: string) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en-IN',
  setLanguage: () => { },
  t: (key: string, defaultText?: string) => defaultText || key,
  languages: INDIAN_LANGUAGES,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    try {
      const stored = localStorage.getItem('cura_language') as LanguageCode;
      if (stored && TRANSLATIONS[stored]) return stored;
    } catch (e) {
      // Ignore
    }
    return 'en-IN';
  });

  const setLanguage = useCallback((newLang: LanguageCode) => {
    if (TRANSLATIONS[newLang]) {
      setLanguageState(newLang);
      try {
        localStorage.setItem('cura_language', newLang);
      } catch (e) {
        // Ignore
      }
    }
  }, []);

  const t = useCallback((key: string, defaultText?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English (India)
    const enDict = TRANSLATIONS['en-IN'];
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return defaultText || key;
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    t,
    languages: INDIAN_LANGUAGES
  }), [language, setLanguage, t]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
